### ISSUE TITLE
add python or install custom packages

### ISSUE THREAD

**Issue by Benni-chan** [linuxserver/docker-sonarr#1]
the development version added support for custom post processing scripts. (i'm currently using a python script to add any anime processed by sonarr to my anidb listing)
it would be great, if you could add python to your docker, so we could easily use this new feature.
or maybe add a functionality to install custom packages via an environment variable.

(currently i've installed python via a docker exec command, but that change would of course be gone, if I have to redownload the docker for any reason.)

**Comment by lonix** [comment]
This was implemented a while back, forgot to close

**Comment by vertigo235** [comment]
How do we add the python package?
