### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by mixxit** [linuxserver/docker-sonarr#101]
Docker image: linuxserver/sonarr:latest

`
"System.NullReferenceException: Object reference not set to an instance of an object\n  at Nancy.Authentication.Forms.FormsAuthentication.EncryptAndSignCookie (System.String cookieValue, Nancy.Authentication.Forms.FormsAuthenticationConfiguration configuration) [0x00000] in <91c66dca293e4531909364de82529d4c>:0 \n  at Nancy.Authentication.Forms.FormsAuthentication.BuildCookie (System.Guid userIdentifier, System.Nullable`1[T] cookieExpiry, Nancy.Authentication.Forms.FormsAuthenticationConfiguration configuration) [0x0000d] in <91c66dca293e4531909364de82529d4c>:0 \n  at Nancy.Authentication.Forms.FormsAuthentication.UserLoggedInRedirectResponse (Nancy.NancyContext context, System.Guid userIdentifier, System.Nullable`1[T] cookieExpiry, System.String fallbackRedirectUrl) [0x001ea] in <91c66dca293e4531909364de82529d4c>:0 \n  at Nancy.Authentication.Forms.ModuleExtensions.LoginAndRedirect (Nancy.INancyModule module, System.Guid userIdentifier, System.Nullable`1[T] cookieExpiry, System.String fallbackRedirectUrl) [0x00006] in <91c66dca293e4531909364de82529d4c>:0 \n  at NzbDrone.Api.Authentication.AuthenticationModule.Login (NzbDrone.Api.Authentication.LoginResource resource) [0x00166] in M:\\BuildAgent\\work\\5d7581516c0ee5b3\\src\\NzbDrone.Api\\Authentication\\AuthenticationModule.cs:46 \n  at NzbDrone.Api.Authentication.AuthenticationModule.<.ctor>b__2_0 (System.Object x) [0x00000] in M:\\BuildAgent\\work\\5d7581516c0ee5b3\\src\\NzbDrone.Api\\Authentication\\AuthenticationModule.cs:21 \n  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)\n  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 "
`
```
<Config>
  <LogLevel>Info</LogLevel>
  <Port>8989</Port>
  <UrlBase></UrlBase>
  <BindAddress>*</BindAddress>
  <SslPort>9898</SslPort>
  <EnableSsl>False</EnableSsl>
  <ApiKey>7585a5d8af7e4460a81d4baea823f641</ApiKey>
  <AuthenticationMethod>Forms</AuthenticationMethod>
  <Branch>master</Branch>
  <LaunchBrowser>True</LaunchBrowser>
  <SslCertHash></SslCertHash>
  <UpdateMechanism>BuiltIn</UpdateMechanism>
</Config>
```

**Comment by homerr** [comment]
@thelamer is this related to what #100 should fix?

**Comment by thelamer** [comment]
Please report this upstream after testing with our current latest image. We simply control the Docker environment this application is running in and cannot debug errors like this unless you think it is related to Docker. 

https://github.com/Sonarr/Sonarr
