### ISSUE TITLE
Build error COPY root/ / - No such file or directory

### ISSUE THREAD

**Issue by EZarnosky** [linuxserver/docker-sonarr#102]
Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-45-generic x86_64)

```
docker version
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:47 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:13 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

----------

I am trying to build the sonarr container in docker, because the hosted container does not have the port 9898 open for HTTPS.

Whenever I use the docker file it fails at the exact same spot:
```
# add local files
COPY root/ /
```
the message is 
`COPY failed: stat /var/lib/docker/tmp/docker-builder328607268/root: no such file or directory`

I know I could just use the port 8989 for HTTPS, but I am now curious why this is failing (fairly new to Docker).

I did look through several of the other docker files for other apps and they have the same line:

`COPY root/ /`
or:
`COPY /root /`

**Comment by aptalca** [comment]
You need to clone the git repo and build from there

But you should really pull the built images from docker hub at linuxserver/sonarr
