### ISSUE TITLE
Please update develop to 2.0.0.5322

### ISSUE THREAD

**Issue by hongkongkiwi** [linuxserver/docker-sonarr#111]
Can I request a rebuild of the "develop" branch?

Currently, when using the develop branch I get: 2.0.0.5321

The latest version from March 28 is 2.0.0.5322.

**Comment by sparklyballs** [comment]
5322 is on the master branch of the image.

**Comment by hongkongkiwi** [comment]
But that's strange, shouldn't develop be the cutting edge?

**Comment by thelamer** [comment]
We ingest versions from their own build environment, we do not have a say in the matter https://services.sonarr.tv/v1/download/develop

If you feel this is an actual issue then report it upstream, but I have to say that the develop tags and even preview tags are their for our partners to have a release channel to test bug fixes and patches. You should not have an expectation of anything. 
For day to day use you should be using the latest tag with the current stable version the developers have decided to release publicly.
