### ISSUE TITLE
SignalR issue with windows share in V3

### ISSUE THREAD

**Issue by bcjacob** [linuxserver/docker-sonarr#112]
I think I am having the issue that I had resolved in V2 with https://github.com/linuxserver/docker-sonarr/issues/88 by adding the - XDG_CONFIG_HOME=/tmp/xdg to my docker-compose file.  In V3 it does not appear to be working.  the .mono keypair directory is still created, but is empty in the mapped windows volume.  SignalR only states it is "connecting" and never "connected" in the browser console.

If I change the config volume to a local directory in my home folder it works fine.  Only with I change back to the shared windows volume does it stop working.

**Comment by aptalca** [comment]
We recommend local paths for config folders. Remote mounts cause a lot of issues as you experienced.
