### ISSUE TITLE
vulnerablecontainers.org found issues

### ISSUE THREAD

**Issue by 87594589-7087-4f7c-b204-e84312ae374c** [linuxserver/docker-sonarr#117]
https://vulnerablecontainers.org/ found 93 Open Vulnerablities for this container.

Direct link to JSON object with all issues listed:

https://vulnerablecontainers.org/reports/linuxserversonarr.json

**Comment by thelamer** [comment]
Reported to github, you need their permission to do shit like this. Don't just bot peoples github issues like this. 

We update the packages from Ubuntu Repos every week more than anyone else on Dockerhub. Report this upstream.

**Comment by 87594589-7087-4f7c-b204-e84312ae374c** [comment]
I happen to not be a bot, but someone who uses this contain but does not like to use usernames that are linkable to a persona.  If I was a bot, I would be a crappy one.

**Comment by thelamer** [comment]
So what are you reporting? Do you even understand that report? That contains reports of stuff in Ubuntu Bionic head packages. What would you propose we do ? 

To me it looks like you are shilling vulnerablecontainers.org and because of that I am deleting this.
