### ISSUE TITLE
Ability to specify base URL via environment variable

### ISSUE THREAD

**Issue by StFS** [linuxserver/docker-sonarr#118]
This feature request might belong in the Sonarr project itself but I decided to give it a try to ask here. I'll probably create an issue there as well.

I'm using docker-compose to start multiple HTPC services, one of which is Sonarr. Other services include Radarr, Deluge and others that all have a web UI.

I want to start an nginx reverse proxy along with these services to simplify how these services can be accessed. However, for Sonarr, that requires me to set the Base URL configuration option.

I can either do that through some rather convoluted config file manipulation but a much simpler solution would be to pass the base URL string into the sonarr container as an environment variable.

Is this something that is possible? If not, would it be possible to add that ability to the docker-sonarr project or does that require an upstream change to the sonarr project itself?

**Comment by aptalca** [comment]
It's not easy for us (too hacky) to set a base url in the docker container unless the upstream project allows a command line argument (some do, but I don't think sonarr does according to [here](https://github.com/Sonarr/Sonarr/wiki/Command-Line-Options))

Your other options are:
- Access sonarr directly the first time and set the base url, then you can remove the port mapping and only access through the reverse proxy
- Use subdomains for the reverse proxy (no base url needed)

If you use our letsencrypt image with cloudflare dns, you can set a wildcard CNAME that covers all subdomains on cloudflare and letsencrypt will get a wildcard cert. That way, you can easily enable the preset proxy confs for all the services by a simple file rename: https://blog.linuxserver.io/2019/04/25/letsencrypt-nginx-starter-guide/
