### ISSUE TITLE
Latest mono 6.0 has permission issues.

### ISSUE THREAD

**Issue by externalz** [linuxserver/docker-sonarr#120]
There looks to be some permission issues on the current mono 6.0 build that i noticed got updated to the current container.
https://forums.sonarr.tv/t/permission-issues-after-mono-6-upgrade/22876/5

I had to roll back to an earlier container version 2.0.0.5322-ls26 for my download handling to work again.

**Comment by j0nnymoe** [comment]
If you need to stick to an older version of mono, use tag `5.14`.
