### ISSUE TITLE
v3 w/mono 5.x?

### ISSUE THREAD

**Issue by glc650** [linuxserver/docker-sonarr#121]
Looks like mono 6 breaks my ability to instantly move completed downloads to my tv directory.  Is there a way to run v3 with version 5.x mono?

**Comment by j0nnymoe** [comment]
Nope, we only provide stable with v5.14 on tag `5.14`

**Comment by centogram** [comment]
+1 Same issue.  Mono seems to be breaking access permissions to mapped drives

**Comment by magnu5** [comment]
Same problem: 
https://forums.sonarr.tv/t/permission-issues-after-mono-6-upgrade/22876

**Comment by thelamer** [comment]
https://github.com/linuxserver/docker-sonarr/pull/125
https://github.com/linuxserver/docker-sonarr/pull/124
https://github.com/linuxserver/docker-sonarr/pull/123
