### ISSUE TITLE
Unable to see /download dir

### ISSUE THREAD

**Issue by rinzes** [linuxserver/docker-sonarr#126]
I am running the latest build on Synology NAS and sonarr is not moving my files to the media dir. After some investigation when I try manual move it is unable to see my config download dir. I have the correct PUID and PGID and no permission problems. Here is the portion of my config

{
         "host_volume_file" : "/downloads/TransmissionVPN/completed",
         "mount_point" : "/downloads",
         "type" : "rw"
      }

**Comment by aptalca** [comment]
Make sure your "/downloads" mount point is exactly the same throughout different containers like sonarr, radarr, transmission, etc.

**Comment by rinzes** [comment]
I have transmission point to /data and Sonarr says this:

Madam.Secretary.S03E04.HDTV.x264-LOL[eztv].mkv
No files found are eligible for import in /data/completed/Madam.Secretary.S03E04.HDTV.x264-LOL[eztv].mk

**Comment by thelamer** [comment]
Do not comment again, the brazen lack of basic understanding of what you are posting is mind boggling.

**Comment by rinzes** [comment]
Did it get your attention? LOL

**Comment by thelamer** [comment]
Enough to now block you from our org
