### ISSUE TITLE
DSM issue

### ISSUE THREAD

**Issue by bnicolae86** [linuxserver/docker-sonarr#128]
I have some issues with versions 619 and 620:

Unknown exception: Failed to get info of /series. Reason: 119 -Unknown error
Failed to get serial number

Sonarr cannot connect to local Download Station on DSM 6.0.2

This exact setup is working on the previous versions. 618 is working fine.

**Comment by thelamer** [comment]
You are running the preview branch I highly suggest you switch to the develop or latest tag for a supported version of Sonarr. 

We do not provide direct application support as we just wrap upstream in a Docker container, but you are welcome to try our discord or Sonarrs
https://discord.gg/M6BvZn5
https://discord.gg/YWrKVTn
