### ISSUE TITLE
Unable to use ENCFS

### ISSUE THREAD

**Issue by sbellassai** [linuxserver/docker-sonarr#129]
I have an ENCFS mount that is mounted by the Host OS (Ubuntu 16.04) that is working as expected in the host OS, but when I try to mount the unencrypted directory as a bind mount in the container, sonarr will not write to it. If I exec into the container, I am about to write to the mount point, and it shows up in the host OS, so it does not _seem_ to be a permissions issue. In the docker logs, Sonarr shows "Access to the path /path/to/move/media/ is denied.
I have tried to touch files as both the root user and abc user when exec's into the container, and both are able to write without issue. 

Host OS: Ubuntu 16.04

Docker container: Sonarr, same issue is happening with Radarr and Deluge containers
Docker logs: https://privatebin.net/?c1fd8609d9987fef#7rcfv3ah1wFEDXWidf2greuPm2yvvumKBd8ptWUeyEtT

Mention if you're using symlinks on any of the volume mounts:No

**Comment by aptalca** [comment]
Likely permissions issue. When you exec into the container, you are running as id 0 (root). Sonarr on the other hand runs as whatever PUID you set
