### ISSUE TITLE
E: dpkg was interupted

### ISSUE THREAD

**Issue by jamitupya** [linuxserver/docker-sonarr#13]
Im receiving the following error when running. it was working but seems to have stopped when i rebooted the host.

running on a synology DS1813+ 

<img width="651" alt="screen shot 2016-04-19 at 2 37 57 am" src="https://cloud.githubusercontent.com/assets/2782038/14617319/ee937426-05d7-11e6-9b9a-9b37f55b15a7.png">

**Comment by lonix** [comment]
Delete the container and Reinstall it. you happend to kill of at the exact moment it did updates.
