### ISSUE TITLE
Error occurred while executing task Backup: Access to the path "/config/config.xml" or "/tmp/sonarr_backup/config.xml.partial~" is denied.

### ISSUE THREAD

**Issue by cdemi** [linuxserver/docker-sonarr#137]
I am using `:preview` container and when I try to run application backup, it looks like the application cannot save in the "/tmp/sonarr_backup/config.xml.partial~" using the provided UID as the environment variable

**Comment by cdemi** [comment]
Adding more information to this. If I use the container as root, I am able to access the `sonarr_backup` folder, however as user `abc` which is the one created on init, I am not able as can be seen in this screenshot:

![image](https://user-images.githubusercontent.com/8025435/68308944-f8b25380-00ad-11ea-8e77-95034703af15.png)

It looks to me like the problem is because the directory `sonarr_backup` is missing the `execute` bit on the directory. I am not sure if this is an application issue or container issue

**Comment by jalmansor** [comment]
Strange, I'm running the preview tag as well and backups work just fine.

```
root@thebin:~ # docker exec -it --user abc sonarr /bin/bash
bash: /root/.bashrc: Permission denied
abc@92495fd6d6fa:/$ cd tmp
abc@92495fd6d6fa:/tmp$ ls -al
total 12
drwxrwxrwt 1 root root 4096 Nov  5 13:11 .
drwxr-xr-x 1 root root 4096 Nov  4 14:21 ..
drwxr-xr-x 2 abc  abc  4096 Nov  6 16:59 sonarr_backup
abc@92495fd6d6fa:/tmp$ cd sonarr_backup/
abc@92495fd6d6fa:/tmp/sonarr_backup$ ls -al
total 62592
drwxr-xr-x 2 abc  abc      4096 Nov  6 16:59 .
drwxrwxrwt 1 root root     4096 Nov  5 13:11 ..
-rw-r--r-- 1 abc  abc       480 Nov  4 14:21 config.xml
-rw-r--r-- 1 abc  abc  64080896 Nov  6 16:11 sonarr.db
abc@92495fd6d6fa:/tmp/sonarr_backup$
```

**Comment by cdemi** [comment]
This is very weird. If you delete the folder inside the container and run the backup from the app again, do you get this result as well?

**Comment by aptalca** [comment]
I just checked my install (also preview tag) and backups are done successfully, both manual and auto.

`/tmp` folder has write permissions for group and others. Sonarr successfully creates the `sonarr_backup` folder, copies the necessary files there, then zips them up and places the zip under /config/Backups

**Comment by aptalca** [comment]
@cdemi please post the command you used to create the container as well as info on your host environment

**Comment by jalmansor** [comment]
> This is very weird. If you delete the folder inside the container and run the backup from the app again, do you get this result as well?

Sorry for the delay, I just ran a fresh instance using the default UID (1000) since my instance was using 1001. First run backup was successful, and deleting the folder and re-running the backup was successful as well. 

@aptalca's info request would be helpful, if you would be so kind.

**Comment by casperse** [comment]
I am facing the same problem:
Error occurred while executing task Backup: Access to the path '/tmp/sonarr_backup' is denied.
I really would like to get a backup before re-installing have allot of settings

**Comment by j0nnymoe** [comment]
@casperse we need some more information about your setup. From all our tests, it's working as expected so until you're able to provide information on your host and how you deployed the container (docker run/compose snippet) then we'll be unable to help.
