### ISSUE TITLE
[libpod] Permissions issue

### ISSUE THREAD

**Issue by Davy1992** [linuxserver/docker-sonarr#139]
## Expected Behavior
You run the usual `podman create` or `podman-compose up -d` and everything works.

## Current Behavior
This is a strange one, whenever you start the container using podman the `/config` directory isn't writeable.
But when you spawn a shell inside it and run `mono --debug NzbDrone.exe -nobrowser -data=/config` or execute `/etc/services.d/sonarr/run` the service starts without any issues, even PUID and PGID are being applied properly.

Then if you were to restart the container the issue comes back, even tho files have already been created.
## Steps to Reproduce
1. Run podman start / restart or podman-compose up -d
2. Be greeted with /config directory isn't writeable error.
3. It doesn't matter if you run the container as **root** or **rootless** or if you use **latest** or **preview** the results are the same.

## Steps to temporarily fix the issue
1. `podman exec -it sonarr bash`
2. `/etc/services.d/sonarr/run`
3. No permission issues

## Environment
**OS:** Fedora 31
**CPU architecture:** x86_64
**How docker service was installed:** It was pre-installed (podman version 1.6.2) using Cgroups v2

## Command used to create docker container (run/create/compose/screenshot)
```
podman create \
  --name=sonarr \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -e UMASK_SET=022 \
  -p 8989:8989 \
  -v /home/user/data/apps/sonarr:/config \
  -v /home/user/data/media/tv:/tv \
  -v /home/user/data/downloads:/downloads \
  linuxserver/sonarr:preview
```

## Docker logs
```
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

chown: changing ownership of '/config'
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
chown: cannot read directory '/config'
[cont-init.d] 30-config: exited 1.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Bootstrap: Starting Sonarr - /usr/lib/sonarr/bin/Sonarr.exe - Version 3.0.3.664 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Trace] DiskProviderBase: Directory '/config' isn't writable. Access to the path "/config/sonarr_write_test.txt" is denied. 


[Fatal] ConsoleApp: EPIC FAIL! 

[v3.0.3.664] NzbDrone.Common.Exceptions.SonarrStartupException: Sonarr failed to start: AppFolder /config is not writable
```

**Comment by aptalca** [comment]
Is /config on a remote mount?

Our containers won't work with rootless docker forks due to the init steps requiring root access (we also neither test or support docker forks).

**Comment by Davy1992** [comment]
> Our containers won't work with rootless docker forks due to the init steps requiring root access (we also neither test or support docker forks).

I see.
I managed to get this working on podman by making the container privileged (`--privileged=true`).

**Comment by illum1n4ti** [comment]
> Is /config on a remote mount?
> 
> Our containers won't work with rootless docker forks due to the init steps requiring root access (we also neither test or support docker forks).

A fork? Podman works way different than docker (Podman has no daemon or service like docker) and running rootless is also more secure. I think we should be careful saying a fork.
