### ISSUE TITLE
nzbgeek not working

### ISSUE THREAD

**Issue by jnthn-b** [linuxserver/docker-sonarr#141]
nzbgeek (usenet indexer) isnt working anymore due to TLS needs an update. On Linux Mono has to be updated to get the indexer working again.
This is from there Site:
If you are getting errors like - cannot establish secure channel - for apps that use the NZBgeek API then your system needs to have TLS (Transport Layer Security) upgraded.

As of Janauary 2020 TLS 1.0 & TLS 1.1 have reached end of life and are no longer supported. 
NZBgeek only allows SSL communications on TLS 1.2 and above as should all websites in which you have secure communications with. 

TLS 1.2 has been out for a long time and there are a small number of geeks who have not kept their systems updated. 
We are also working towards supporting TLS 1.3 so keeping updated is a good thing.

For the following applications you will need to ensure certain minimums are in place to carry out secure communications:

Sonarr & Radarr

Windows operating systems require .NET updated.
Linux operating systems require mono updated.

Would be amazing to get that updated.

**Comment by aptalca** [comment]
You're assuming that the Mono build we ship doesn't support TLS 1.2. Please provide info to support that

**Comment by jnthn-b** [comment]
woops im sorry. Must have been another issue. Now i got it working again. But thanks for your time!
