### ISSUE TITLE
Add LFTP to Sonarr Image

### ISSUE THREAD

**Issue by joltman80** [linuxserver/docker-sonarr#143]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
I've got a script that executes LFTP to pull down files from my seedbox.  LFTP is not installed in the docker container natively.  This means my script won't run.

## Current Behavior
LFTP isn't installed so my script doesn't run

## Steps to Reproduce

1.  LFTP isn't installed.
2.  I ran "apt install lftp"
3.  My script ran correctly.
4.

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**      
Ubuntu 18.04 LTS
Docker-Compose

**Comment by aptalca** [comment]
See here for customizing: https://blog.linuxserver.io/2019/09/14/customizing-our-containers/
