### ISSUE TITLE
"Failed to get runtime from the file, make sure mediainfo is available"

### ISSUE THREAD

**Issue by ErroneousBosch** [linuxserver/docker-sonarr#157]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

Noticing an error message in the logs: Failed to get runtime from the file, make sure mediainfo is available

------------------------------

## Expected Behavior

MediaInfo should load normally
## Current Behavior

Error message in log: Failed to get runtime from the file, make sure mediainfo is available

## Steps to Reproduce

1. Run Sonarr in Docker
2. Download items
3. Check logs for when Sonarr scans items to add
4.

## Environment
**OS:**      Docker runing on Ubuntu 18.04 LTS
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:** 
As a system service? no idea what you are asking

     

## Command used to create docker container (run/create/compose/screenshot)

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK_SET=022 #optional
    volumes:
      - /docker/sonarr:/config
      - '/media/TV:/tv'
      - '/media/Anime:/anime'
      - /media/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

## Docker logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Sonarr: https://sonarr.tv/donate

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Bootstrap: Starting Sonarr - /app/sonarr/bin/NzbDrone.exe - Version 2.0.0.5344 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] Router: Application mode: Interactive 
[Info] MigrationLogger: *** Migrating data source=/config/nzbdrone.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] MigrationLogger: *** Migrating data source=/config/logs.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] OwinHostController: Listening on the following URLs: 
[Info] OwinHostController:   http://*:8989/ 
[Info] NancyBootstrapper: Starting Web Server 
[Info] RssSyncService: Starting RSS Sync 
[Warn] Torznab: Indexer Torrentz2 rss sync didn't cover the period between 5/21/2020 12:34:30 PM and 5/21/2020 12:52:43 PM UTC. Search may be required. 
[Warn] Torznab: Indexer SkyTorrents rss sync didn't cover the period between 5/21/2020 12:35:22 PM and 5/21/2020 12:47:58 PM UTC. Search may be required. 
[Warn] Torznab: Indexer Torrent Downloads rss sync didn't cover the period between 5/21/2020 12:42:49 PM and 5/21/2020 12:58:35 PM UTC. Search may be required. 
[Info] DownloadDecisionMaker: Processing 695 releases 
[Info] RssSyncService: RSS Sync Completed. Reports found: 695, Reports grabbed: 0 

[Warn] VideoFileInfoReader: Unable to open media info from file: /downloads/filename.mkv 
[Error] DetectSample: Failed to get runtime from the file, make sure mediainfo is available

**Comment by j0nnymoe** [comment]
Please fill out the requested information in the template.

**Comment by ErroneousBosch** [comment]
Which pertinent detail are you missing?

**Comment by CHBMB** [comment]
@ErroneousBosch Well, the container run command/docker compose, full logs.  Whether docker was installed from the Ubuntu default repos or whether you installed it from docker's own repository (to be honest this is probably less important)  but the first two, without them, we'd be shooting in the dark, which is why we made the template to start with.

**Comment by ErroneousBosch** [comment]
YOu can cancel this. turns out it is a 0-byte file. sorry to raise a fuss

**Comment by Noext** [comment]
hello, i got the same issue but my files are valid
