### ISSUE TITLE
not added with the "standard" type.

### ISSUE THREAD

**Issue by Anzic23** [linuxserver/docker-sonarr#162]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
add a series with the "standard" type

## Current Behavior

Request Failed. POST /api/series: Error converting value "standart" to type 'NzbDrone.Core.Tv.SeriesTypes'. Path 'seriesType', line 1, position 695.
## Steps to Reproduce

1. use https://github.com/Memodota/gramarr
2. try to add a series with the "standard" type
3. error in log
4. if add if added with the daily type, it is added normally

## Environment
**OS:**      Synology 
**CPU architecture:** x86_64
**How docker service was installed:**      

## Command used to create docker container (run/create/compose/screenshot)

[docker-compose sonarr.txt](https://github.com/linuxserver/docker-sonarr/files/4902724/docker-compose.sonarr.txt)

## Docker logs

[log.log](https://github.com/linuxserver/docker-sonarr/files/4902728/log.log)

**Comment by j0nnymoe** [comment]
This isn't a container issue, you need to report this to sonarr directly.
