### ISSUE TITLE
Import failed, path does not exist or is not accessible by Sonarr: SOLUTION

### ISSUE THREAD

**Issue by adit-s** [linuxserver/docker-sonarr#169]
Sonarr recently started giving the error "Import failed, path does not exist or is not accessible by Sonarr: ..." for every episode downloaded from rarbg.to. (It may affect other sites as well, but I only tested with rarbg)
I spent a lot of time (too much) trying to figure out what was going on. I thought I'd post my findings here so it can help others who may be having the same issue.

**The error is generated when downloading with qBittorrent 4.3 or higher.**
If you are using Sonarr with qBittorrent and run into this issue, **go back to qBittorrent 4.2.5**. In my case, that fixed the problem.

Hopefully, this post will help others and save you a lot of time trying to figure it out.

**Comment by y2kboy23** [comment]
Looks like they just merged changes that accounts for qBittorrent 4.3 (https://github.com/Sonarr/Sonarr/commit/813f8869202b54048db8d792ee6c3f0d060dbd72).  Any way to pull this commit into the existing docker images?

**Comment by CHBMB** [comment]
@y2kboy23 Our build process is automated, once it's pushed upstream to our endpoint, we will build.

**Comment by CHBMB** [comment]
@adit-s @y2kboy23 Can you try this https://github.com/linuxserver/docker-sonarr/releases/tag/3.0.4.1000-ls74

**Comment by y2kboy23** [comment]
Upgraded from v2 to v3.0.4.1000 and everything started working again.  Thanks for the assistance @CHBMB.
