### ISSUE TITLE
3.0.0.3989: Permission denied (Unraid)

### ISSUE THREAD

**Issue by PrincessLuna2253** [linuxserver/docker-sonarr#170]
After the latest update to the nightly Radarr container, 3.0.0.3989, Radarr no longer starts and outputs a lot of permission denied errors to the log.

-----------------------

foreground: warning: unable to spawn /docker-mods: Permission denied

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...
foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/10-adduser: Permission denied

[cont-init.d] 10-adduser: exited 127.
[cont-init.d] 30-config: executing...
foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/30-config: Permission denied

[cont-init.d] 30-config: exited 127.
[cont-init.d] 99-custom-scripts: executing...
foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/99-custom-scripts: Permission denied

[cont-init.d] 99-custom-scripts: exited 127.
[cont-init.d] done.
[services.d] starting services
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise radarr: warning: unable to spawn ./run - waiting 10 seconds

[services.d] done.
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise radarr: warning: unable to spawn ./run - waiting 10 seconds

s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise radarr: warning: unable to spawn ./run - waiting 10 seconds

----------------------

I am running the container on Unraid 6.8.3. I rolled the container back to the previous release, 3.0.0.3790, and it works fine again, so I don't think it's Unraid or something I did. I can't think of anything else to add here, but I'm pretty stupid so if more info is needed let me know and I'll get it.

**Comment by aptalca** [comment]
Radarr has a new build pushed earlier today, which fixes it.

And btw, this is the sonarr repo, not radarr

**Comment by PrincessLuna2253** [comment]
Welp. I did say I was stupid. I can't even keep my *arrs straight haha.

Glad to know it will be fixed, thanks!
