### ISSUE TITLE
Consistent tag naming with radarr

### ISSUE THREAD

**Issue by braunsonm** [linuxserver/docker-sonarr#171]
## Expected Behavior
Radarr and Sonarr images should use the same naming conventions.

## Current Behavior
Radarr images now use `nightly` for V3 where sonarr still uses `preview`

**Comment by aptalca** [comment]
They are two different projects with different naming schemes.

**Comment by braunsonm** [comment]
Not really. It's a fork and sonarr uses the same branch naming. It's only this container that differs. @aptalca

**Comment by Roxedus** [comment]
Well, radarr has merged it's v3 code into their nightly tag, Sonarr has not.
