### ISSUE TITLE
V3 Import Lists Failing

### ISSUE THREAD

**Issue by johnkennyuk** [linuxserver/docker-sonarr#172]
Describe the bug
I have been trying to use Trakt lists in Sonarr V3, they do work with Limit of 100 +/- few but the lists ive been trying to use have entries in 1000 and above range. But when setting the limit to 250 it seems the import crashes and fails to add any new entries. I assumed that using low limits which work like 100 would allow me to use these large lists as I assumed that Sonarr would import 100 new shows every run but its not its just importing the first 100 and then the first 100 every run after that??? So that wont work for my needs I need to be able to run Lists with limits 1000 up???

Screenshots
image
![image](https://user-images.githubusercontent.com/64958468/99261992-54f99880-2815-11eb-87a4-828f37753293.png)

Logs
https://gist.github.com/johnkennyuk/eb2702e793d6f18435e3b6909a4fd464
https://gist.github.com/johnkennyuk/eb050e6ce5a95f2ae8977dc651f5f8a4

System Information

Sonarr Version: 3.0.4.1006
Package Version 3.0.4.1006-ls77 by linuxserver.io

Operating System: Ubuntu server 18.04 LTS

Mono Version 5.20.1.34

UI Bugs:
NA

Additional context

**Comment by Roxedus** [comment]
This is a app issue, not a container issue.

**Comment by johnkennyuk** [comment]
> This is a app issue, not a container issue.

Surely its still valid here seeing as this is the source app even if it is in container, although wasnt sure myself so posted issue here and issue here https://github.com/Sonarr/Sonarr/issues/4100.

**Comment by j0nnymoe** [comment]
We give support for issues that could be caused by misconfiguration with deployment of the container, any issues with the app itself needs to be asked upstream :)
