### ISSUE TITLE
s6-envuidgid: fatal: unknown user: root

### ISSUE THREAD

**Issue by a31p18** [linuxserver/docker-sonarr#178]
I have been running the preview branch on my Unraid 6.9.0-rc2 server for 6 months+ now. Today, it's boot looping. The logs are below.

/usr/bin/with-contenv: line 6: /usr/bin/with-contenvb: Success
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
s6-envuidgid: fatal: unknown user: root
s6-envuidgid: fatal: unknown user: root
s6-envuidgid: fatal: unknown user: root
s6-envuidgid: fatal: unknown user: root
s6-envuidgid: fatal: unknown user: root
s6-envuidgid: fatal: unknown user: root
s6-envuidgid: fatal: unknown user: root
s6-envuidgid: fatal: unknown user: root
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/01-envfile: Permission denied

[cont-init.d] 01-envfile: exited 127.
[cont-init.d] 10-adduser: executing...
foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/10-adduser: Permission denied

[cont-init.d] 10-adduser: exited 127.
[cont-init.d] 30-config: executing...
foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/30-config: Permission denied

[cont-init.d] 30-config: exited 127.
[cont-init.d] 99-custom-scripts: executing...
foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/99-custom-scripts: Permission denied

[cont-init.d] 99-custom-scripts: exited 127.
[cont-init.d] done.
[services.d] starting services
s6-supervise sonarr: warning: unable to spawn ./run - waiting 10 seconds

s6-supervise (child): fatal: unable to exec run: Permission denied
[services.d] done.
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise sonarr: warning: unable to spawn ./run - waiting 10 seconds

s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise sonarr: warning: unable to spawn ./run - waiting 10 seconds

s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise sonarr: warning: unable to spawn ./run - waiting 10 seconds

**Comment by a31p18** [comment]
command used to run : /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='sonarr' --net='bridge' -e TZ="Europe/London" -e HOST_OS="Unraid" -e 'PUID'='0' -e 'PGID'='0' -p '8989:8989/tcp' -v '/mnt/user/media/shows':'/tv':'rw' -v '/mnt/user/appdata/sonarr':'/config':'rw' -v '/mnt/user/downloads/':'/downloads':'rw' --restart always 'linuxserver/sonarr:preview' (extracted from unraid)

**Comment by aptalca** [comment]
Don't run as root. Use `99:100`

**Comment by a31p18** [comment]
Thanks @aptalca. To anyone who has misconfigured sonarr's docker on Unraid and are looking for a way to resolve this issue, @aptalca resolution won't be enough. You have to re-create the docker.img first (stop the docker service, delete the img and then start the service again) then re-create sonarr's docker from Unraid's user template and then apply @aptalca fix.

**Comment by tobbenb** [comment]
It is not needed to delete the docker.img!
