### ISSUE TITLE
Update latest to v3

### ISSUE THREAD

**Issue by scottsuch** [linuxserver/docker-sonarr#179]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Bump the container to include sonarr v3!

## Current Behavior
The stable container is still running sonarr v2.

## Alternatives Considered
I should create a PR. I'll try to get to that at some point.

**Comment by Roxedus** [comment]
Working on it

**Comment by scottsuch** [comment]
Awesome, thank you so much!

**Comment by rdrr** [comment]
Maybe change the documentation on hub.docker.com until the change is made?  I spent a couple frustrating hours trying to get it to work before realizing the 'latest' is still v2.  Thanks!

**Comment by Roxedus** [comment]
> Maybe change the documentation on hub.docker.com until the change is made? I spent a couple frustrating hours trying to get it to work before realizing the 'latest' is still v2. Thanks!

:latest is v3, been for 26 days

**Comment by rdrr** [comment]
Huh...I'm sorry.  I don't know what is going on then.  I deleted the image and pulled latest and it still has a build date of 2/16 and v2.0.0.5344, but it's tagged latest.

Must be an issued on my end.  Got a lot more to learn.  Sorry again and thanks

**Comment by bunjiboys** [comment]
@rdrr One thing that usually catches me out (and did again today when I was upgrading) is to remember to not just stop the old container, but to actually remove it from the host, if you are using named containers. It wont change the image id until the existing one is removed
