### ISSUE TITLE
Tag Preview to Latest

### ISSUE THREAD

**Issue by carlsimmons81** [linuxserver/docker-sonarr#185]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Moving from the Preview Tag to Latest should give me Version 3 but it doesn't.  I get downgraded to V2.
## Current Behavior

Version 2 is what's given to me.

## Steps to Reproduce

1. Edit Container
2. Change tag from sonarr:preview to Sonarr:latest
3. Launch Sonarr which is V2.
4.

## Environment
**OS:** UnRAID
**CPU architecture:** x86 (AMD RYZEN 3700X)
**How docker service was installed:** Native app for docker in UnRAID
 Linusserver

<img width="1603" alt="Screen Shot 2021-03-11 at 4 43 45 PM" src="https://user-images.githubusercontent.com/61630814/110874654-fe630f00-8288-11eb-954f-c17cb6d1146b.png">

**Comment by aptalca** [comment]
You just have an old image for the latest tag, which unraid is using by default. Turn on advanced and delete that latest, prior to switch from preview, or force an update after switch.

**Comment by JasonLandbridge** [comment]
@aptalca, Thank you very much!
