### ISSUE TITLE
Fail to identify episode larger than 1000.

### ISSUE THREAD

**Issue by Shad0w1and** [linuxserver/docker-sonarr#187]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

For episodes over 1001, they should be imported properly.
## Current Behavior

Detective Conan is now over 1000 ep. Apparently, ep 1001 is identified as season 10 ep 01 which been grabbed to ep 255(10x01).
## Steps to Reproduce

1. Automatic search would not grab any episodes over 1000.
2. Interactive search can search for Detective Conan Ep 1001, but when import they alert for cannot identify the ep number.
3. Episode 1001 is identified as season 10 ep 01 which been grabbed to ep 255(10x01).

## Environment
**OS: Linux (QNAP QTS)**
**CPU architecture:** Arm64
**How docker service was installed:**

official repo pulled

**Comment by Roxedus** [comment]
This is not a issue with the image, so this would be the incorrect place to file this issue. However in this case Sonarr has already fixed this, so it will be in a later release.

**Comment by Shad0w1and** [comment]
ok just saw develop branch has been updated. sorry for that. guess I will stay develop the branch for a while until the stable master branch is updated. Thanks.
