### ISSUE TITLE
unable to spawn ./run

### ISSUE THREAD

**Issue by Xat59** [linuxserver/docker-sonarr#19]
Hi guys,

when running on CentOS 7 , I get this in the container :
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise sonarr: warning: unable to spawn ./run - waiting 10 seconds

I run the container with :
docker run --name sonarr -d -p 8989:8989 -e PUID=1000 -e PGID=1000 -v /dev/rtc:/dev/rtc:ro -v /home/docker/:/config -v /home/docker/var/transmission/Downloads:/tv -v /home/docker/var/transmission/Downloads:/downloads docker.io/linuxserver/sonarr

I also tried with :
docker run -d --name=test -p 8989:8989 linuxserver/sonarr
But same behavior.

I am able to bypass this problem by rewriting the Dockerfile with :
VOLUME /run

But after building and running, I'm not able to see the 'mono' process and I have to run it manually.

Thank a lot.

**Comment by sparklyballs** [comment]
it was unclear from the chat in IRC as to whether you've modified the dockerfile or attendant files from the git repository.

that error sounds to me like you're trying to add in a service file.

**Comment by Xat59** [comment]
Actually these errors come from the official image : linuxserver/sonarr .

Indeed I also tried by modifying the Dockerfile in order to bypass this error. But the current issue use the official image.

Thank !

**Comment by sparklyballs** [comment]
i'm not convinved that you are using the container as written

it's possible that you still have the image (the part that comes from the hub or is written by a Dockerfile locally) 

can you do 

docker pull linuxserver/sonarr 

before any new runs.

the error you're reporting is usually from either adding a new services folder with no run command in it, or a run command with no shebang.

**Comment by Xat59** [comment]
Here is my output :

[root@localhost ~]# docker pull linuxserver/sonarr
Using default tag: latest
Trying to pull repository docker.io/linuxserver/sonarr ... 
latest: Pulling from docker.io/linuxserver/sonarr
f069f1d21059: Already exists 
ecbeec5633cf: Already exists 
ea6f18256d63: Already exists 
54bde7b02897: Already exists 
3e417c137cb6: Already exists 
b4b71dd23af6: Already exists 
1adb4a6470d1: Already exists 
7065ddfad516: Pull complete 
d2a37a466d14: Pull complete 
Digest: sha256:8b4c418e8c11e68f3a1bb75b05e65795a6f56f35e5c42d945afdf535e14ff174
Status: Downloaded newer image for docker.io/linuxserver/sonarr:latest

[root@localhost ~]# docker ps
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS              PORTS                                          NAMES
ace3ab8fe010        1b3f218ac40b           "/init"             23 hours ago        Up 23 hours         0.0.0.0:8989->8989/tcp                         test

[root@localhost ~]# docker stop ace3ab8fe010
ace3ab8fe010

[root@localhost ~]# docker rm ace3ab8fe010
ace3ab8fe010

[root@localhost ~]# docker run --name sonarr -d -p 8989:8989 -e PUID=1000 -e PGID=1000 -v /dev/rtc:/dev/rtc:ro -v /home/docker/:/config -v /home/docker/var/transmission/Downloads:/tv -v /home/docker/var/transmission/Downloads:/downloads docker.io/linuxserver/sonarr                                                                                                                                                             
84c9e91b941f987917b98b81409d7e34b85af053e8449a3f56e67763fc20bb03

[root@localhost ~]# docker ps
CONTAINER ID        IMAGE                          COMMAND             CREATED             STATUS              PORTS                                          NAMES
84c9e91b941f        docker.io/linuxserver/sonarr   "/init"             4 seconds ago       Up 2 seconds        0.0.0.0:8989->8989/tcp                         sonarr
0a1d3ea4df31        dperson/transmission           "transmission.sh"   12 days ago         Up 12 days          0.0.0.0:9091->9091/tcp, 51413/tcp, 51413/udp   romantic_shaw

[root@localhost ~]# docker logs --tail=10 -f 84c9e91b941f
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
s6-supervise sonarr: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: Permission denied
[services.d] done.
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise sonarr: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise sonarr: warning: unable to spawn ./run - waiting 10 seconds

As you can see I have the behavior I said with the image from the hub.

Thank

**Comment by sparklyballs** [comment]
why is your docker pulling from docker.io ?

**Comment by Xat59** [comment]
docker.io is the only one registry configured . Is the default one

**Comment by Xat59** [comment]
Here is the docker info :

[root@localhost ~]# docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-8:2-915111-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.045 GB
 Data Space Total: 107.4 GB
 Data Space Available: 16.48 GB
 Metadata Space Used: 1.79 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Execution Driver: native-0.2
Logging Driver: journald
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.14.32-xxxx-grs-ipv6-64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 3.834 GiB
Name: localhost
ID: CZMG:XOEY:XI2R:UHA2:MWHC:XU7S:VVAL:6BXI:WE5S:K64W:L47W:7FE6
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Registries: docker.io (secure)

**Comment by sparklyballs** [comment]
solved, the default centos7 docker package is the root cause.
as per the users testing, the solution is to the official docker repository as per.

https://docs.docker.com/engine/installation/linux/centos/

**Comment by Xat59** [comment]
Ok I find out the problem thank to your support .

I had the 'docker' package from the centos 7 extra repository (does not work) :
Nom                 : docker
Architecture        : x86_64
Version             : 1.10.3
Révision            : 46.el7.centos.10
Taille              : 9.5 M
Dépôt               : extras/7/x86_64

This package does not work with your image as I said in my first post.

Now I tried with the 'docker-engine' package from the official docker repository (works fine) :
Nom                 : docker-engine
Architecture        : x86_64
Version             : 1.12.1
Révision            : 1.el7.centos
Taille              : 79 M
Dépôt               : installed
Depuis le dépôt     : dockerrepo

Don't know really the difference between them, but the problem is solved.

Thank you.
