### ISSUE TITLE
Error with SignalR with Bazarr

### ISSUE THREAD

**Issue by ajdiazv** [linuxserver/docker-sonarr#194]
Hi, I have this following issue about few days.

The problem:
Bazarr hang up when trying to config with Sonarr (with Radarr works fine), bazarr keep saying "BAZARR cannot parse JSON returned by SignalR feed. This is a known issue when Sonarr doesn't have write permission to it's /config/xdg directory", and I don't have any "xdg" directory on Sonarr Config Directory. With Bazarr support trying various alternatives, but with no luck.

The actions I took:
I delete everything about my htpc configuration, this include, delete all images in docker, delete all volumes in docker, delete all config directories... the only thing that, of course, i don't delete was my media files.
I install every app again with "docker-compose up", all images downloaded and services up again.
Again, no "xdg" directory on Sonarr, and bazarr config of Sonarr get stuck again with the same messages...

## Environment
**OS: Docker Desktop 3.5.2 (66501), Engine:20.10.7 on Windows 10 WSL 2 Ubuntu 20.04 LTS
**CPU architecture:** x86_64 (Intel i5)
**How docker service was installed:**
From Official WebPage.

## Command used to create docker container (run/create/compose/screenshot)
Docker-Compose.yml
***---***
sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    #network_mode: "host"
    environment:
      - PUID=${PUID} # default user  id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ}     # timezone, defined in .env
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
      - TP_THEME=plex
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config # config files
      - ${ROOT}/downloads:/downloads  # download folder
      - ${MediaDrv}/Series:/tv        # TV Shows Folder
          
    ports:
      - 8989:8989 # port for sonarr web UI to be reacheable from local network
***----    ***
Sonarr Version: 3.0.6.1265, Package Version 3.0.6.1265-ls113 by linuxserver.io
Mono Version 5.20.1.34
Bazarr Version 0.9.6
Radarr Version 3.2.2.5080

## Docker logs

[docker_sonarr_log.txt](https://github.com/linuxserver/docker-sonarr/files/6862445/docker_sonarr_log.txt)

**Comment by luizbird** [comment]
I'm having the same issue, even on a fresh install, on OpenMediaVault v5.6.13-1 (Usul), installed via Portainer.

**Comment by serkansmg** [comment]
same here.. any update?

**Comment by bakerboy448** [comment]
The issue for you both is more than likely the permissions on /config are incorrect.

namely either too permissive or too restrictive

I believe 775 should work

**Comment by Pedernalesiii** [comment]
Hi everyone...
If you are using Windows with WSL 2 for Docker... the solution is not in docker config or docker-compose.
The solution is in WSL 2 config on Windows. Docker could have all permission for their dockers machines, but docker doesn't have the permission from Windows in WSL.
You have to check the file WSL.CONF in your WSL Linux Distribution.
Once inside WSL linux prompt, go to /etc directory.... their must exist a file called "wsl.conf"
Edit, and add the following line if not exist..

options = "uid=1000,gid=1000,metadata,umask=22"

This, obviously if you have docker machines and docker tu use uid and gid = 1000, if not, change it for uid and gid that you are using....
After that, shutdown docker and reboot pc.

This change work fine for me, and never had a new error about permission between docker machines.
