### ISSUE TITLE
Feature Request: Secure connection

### ISSUE THREAD

**Issue by skidelo** [linuxserver/docker-sonarr#2]
Anyway we can get TLS/SSL support with Sonarr?! :-)
See here:
https://github.com/Sonarr/Sonarr/wiki/SSL

Looks like the docker would need 'httpcfg'.  And then setup to run the command when the container is first installed.

**Comment by lonix** [comment]
As we see this, we are required to use a windows tool to create the certificate, which to us, linux users is discusting. However this leaves us with two options for implimentation.

1. We can create a static certificat, but that would kinda defeat it's own purpose. 

2. We could provide you with a option to insert your own certificate.

tl;dr we might be doing option 2.

**Comment by skidelo** [comment]
Option 2 works for me! I have my own certificate.  

Other docker containers that implement this will scan for a certificate and key in a mapped configuration folder.  If you need help testing I'd be glad to help.  My certificate is signed by a proper CA.

**Comment by skidelo** [comment]
What was the reason for marking it as won't fix?  If it's time, maybe I can take a look.

**Comment by lonix** [comment]
time.. feel free im happy to look at any pr :)
