### ISSUE TITLE
EPIC FAIL! Database is locked

### ISSUE THREAD

**Issue by ywLBhGk2noZLbY7** [linuxserver/docker-sonarr#20]
Trying to run Sonarr on Windows using the following command (I realize the /dev/rtc is completely useless, but heyho):-

`docker create -e PUID=${PID} -e PGID=${GID} --name sonarr --hostname sonarr --network usenet -p 8989:8989 -v /dev/rtc:/dev/rtc:ro -v "/c/Users/${USER}/Docker/sonarr/config":/config -v "/c/Users/${USER}/Docker/sonarr/tv/":/tv -v "/c/Users/${USER}/Docker/sonarr/downloads/":/downloads linuxserver/sonarr:latest`

Results in:-

```
[Fatal] ConsoleApp: EPIC FAIL!

[v2.0.0.4230] System.Data.SQLite.SQLiteException: database is locked
database is locked
  at System.Data.SQLite.SQLite3.Step (System.Data.SQLite.SQLiteStatement stmt) <0x40e6dde0 + 0x002ab> in <filename unknown>:0
  at System.Data.SQLite.SQLiteDataReader.NextResult () <0x40e6b150 + 0x00741> in <filename unknown>:0
  at System.Data.SQLite.SQLiteDataReader..ctor (System.Data.SQLite.SQLiteCommand cmd, CommandBehavior behave) <0x40e6aa70 + 0x002b9> in <filename unknown>:0
  at (wrapper remoting-invoke-with-check) System.Data.SQLite.SQLiteDataReader:.ctor (System.Data.SQLite.SQLiteCommand,System.Data.CommandBehavior)
  at System.Data.SQLite.SQLiteCommand.ExecuteReader (CommandBehavior behavior) <0x40e6a070 + 0x00043> in <filename unknown>:0
  at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery (CommandBehavior behavior) <0x40e69fb0 + 0x00037> in <filename unknown>:0
  at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery () <0x40e69f80 + 0x0001b> in <filename unknown>:0
  at System.Data.SQLite.SQLiteConnection.Open () <0x40e62470 + 0x01f7c> in <filename unknown>:0
```

Where as the same command, but `/command` not being mounted (And instead mounting to `/config2` (obviously doesn't save your configuration though!)) results in it working fine:-

`docker create -e PUID=${PID}-e PGID=${GID} --name sonarr --hostname sonarr --network usenet -p 8989:8989 -v /dev/rtc:/dev/rtc:ro -v "/c/Users/${USER}/Docker/sonarr/config":/config2 -v "/c/Users/${USER}/Docker/sonarr/tv/":/tv -v "/c/Users/${USER}/Docker/sonarr/downloads/":/downloads linuxserver/sonarr:latest`

**Comment by sparklyballs** [comment]
i'm not fully sure of the particulars of the setup of docker in windows (not a windows user), but i know that sqlite doesn't operate with symlinked folders.

that may be the issue here, or the perennial issue of permissions.

**Comment by ywLBhGk2noZLbY7** [comment]
I am not a Windows user by choice, but I have to use it on my laptop for other purposes. I tested it my other Linux-based computers and it seems to work fine there, so I suppose it is just a Windows issue.

I just checked and Docker seems to mount files using CIFS, [this blog](https://support.shotgunsoftware.com/hc/en-us/community/posts/209491808-Getting-database-is-locked-on-NFS-and-CIFS-setup) seems to state that you need the "nolock" mount option to get it working, which Docker doesn't seem to use.

I'll look into this more tomorrow and get back to you if there's anything that your docker-file specifically can update to incorporate Windows compatibility, other than that, yeah, seems to be SQLite. Thanks anyway!

**Comment by IronicBadger** [comment]
I'd question whether just running Sonarr natively on Windows wouldn't be a better shout. Docker for Windows / Mac is 'production ready' according to them but in my experience is far from it.

**Comment by ywLBhGk2noZLbY7** [comment]
@IronicBadger Honestly, the main reason why I was using it on Windows is simply because it's my local box and am about to reconfigure my NAS (Running Linux). I'm planning on using my NAS with Docker, so I thought I might be able to sneak in a quick "tutorial" session before I do it on my real configuration. Didn't go to plan.

In the end, I leased a DigitalOcean droplet for a few hours and tried it out there, where everything worked perfectly.

**Comment by firecube** [comment]
I had the same on Windows.  See this page for what is going on and a work around that works depending on how you are using docker. https://forums.docker.com/t/sqlite-db-locked-when-on-a-windows-volume/13757/4

The key is this option 'nobrl' in the mount which could be specified in Docker for Windows but no longer works.  I am using a Hyper-V VM managed with docker-machine and so have to add the mount manually so it was the fix I was looking for.
