### ISSUE TITLE
A list of GUID instead of a single one

### ISSUE THREAD

**Issue by alexandery** [linuxserver/docker-sonarr#200]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Ability to assign multiple group IDs instead of a single one. In my case I need the container to access few host volumes which have permissions assigned to different groups. The user running Sonarr belongs to those groups, but the container fails because I can assign only one group ID.

P.S. Bunch of other images support list of group IDs and those work well.

## Current Behavior
Single GUID which breaks the app in a setup where different directories have group based permissions.

## Alternatives Considered
Uhm... Find another image from another provider?

**Comment by Roxedus** [comment]
This is not something we are going to invest time into, it's also not something that could be solved in this repository.
