### ISSUE TITLE
Cannot connect to both indexers and download clients when using privoxy proxy

### ISSUE THREAD

**Issue by metaMMA** [linuxserver/docker-sonarr#204]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Successful connections

## Current Behavior

All indexers fail and all download clients are unavailable 

## Steps to Reproduce

1. run a docker container that enables Provoxy (or some other method to run Privoxy)
2. add proxy (Privoxy) IP and port to sonarr general settings, and enable proxy
3. test download clients
4. test indexers

## Environment
**OS:** unRAID
**CPU architecture:** x86_64
**How docker service was installed:** unRAID app store

## Command used to create docker container (run/create/compose/screenshot)

used unRAID app store

## Docker logs
[sonarr_deluge_issue.txt](https://github.com/linuxserver/docker-sonarr/files/7787086/sonarr_deluge_issue.txt)
[sonarr_indexer_issues.txt](https://github.com/linuxserver/docker-sonarr/files/7787088/sonarr_indexer_issues.txt)

**Comment by Roxedus** [comment]
This is not a container issue.
