### ISSUE TITLE
Unable to pull new version (3.0.8)

### ISSUE THREAD

**Issue by Vortilion** [linuxserver/docker-sonarr#214]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
sudo docker-compose pull sonarr will pull new image for sonar 3.0.8

## Current Behavior
https://i.imgur.com/jvVntIj.png)](https://i.imgur.com/jvVntIj.png

## Steps to Reproduce
sudo docker-compose stop sonarr
sudo docker-compose pull sonarr

## Environment
**OS:**
Ubuntu 21.10 (Virtual Machine)

**How docker service was installed:**
docker repo

**Comment by Vortilion** [comment]
It seems that it suddenly only works if i remove the prefix "lscr.io/" from the docker-compose-file. Why is that? Why did it work before WITH the prefix?

**Comment by j0nnymoe** [comment]
https://www.githubstatus.com/ github are currently having issues.

**Comment by Vortilion** [comment]
Oh, I didnt see the connection there? thx...

**Comment by j0nnymoe** [comment]
lscr.io/ points to github itself.

**Comment by Vortilion** [comment]
Thanks, didnt know that!
