### ISSUE TITLE
Sonarr unable to get runtime on some .mkv files leading to failure when importing

### ISSUE THREAD

**Issue by rajivravio** [linuxserver/docker-sonarr#227]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Files from downloads folder should be imported to correct season folder in Plex TV shows library

## Current Behavior

Some mkv files are not moved. Checking the logs, these files have reportedly a runtime of 0 or it failed to get runtime for the file. The episode files are valid and works as expected when manually imported. Checking the mediainfo in the file manually shows correct runtime. Permissions on the files are correct. I manually updated mediainfo to latest locally:

`MediaInfo Command line,
MediaInfoLib - v21.09`

```
Failed to get runtime from the file, make sure mediainfo is available
has a runtime of 0, is it a valid video file?
```

## Steps to Reproduce

1. Download full seasons in mkv format
2. Wait for the download to complete
3. Wait for the completed downloads to be moved to the watched downloads folder
4. Wait for Sonarr to scan the watched downloads folder
5. Sonarr imports some and then throws this error for the rest

## Environment
**OS:** UBUNTU Linux 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
**CPU architecture:** x86_64/
**How docker service was installed:** Docker file

# Sonarr - TV Shows management
  sonarr:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    networks:
      npm_proxy:
        ipv4_address: 192.168.89.167
    ports:
      - "8989:8989"
    volumes:
      - $DOCKERDIR/appdata/sonarr:/config
      - $DATADIR/downloads:/data/downloads
      - $DATADIR/media:/data/media
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      <<: *default-tz-puid-pgid

## Command used to create docker container (run/create/compose/screenshot)

docker-compose -f ~/docker/docker-compose.yml up -d

## Docker logs
**removed as mentions copywrited content**
[Info] Auth: Auth-Unauthorized ip url 'http://
[Info] Auth: Auth-Unauthorized ip url 'http://' ,
[Info] Auth: Auth-Unauthorized ip  url 'http://' ,

SONARR LOGS:

**removed as mentions copywrited content**`

**Comment by rajivravio** [comment]
Anyone got any ideas on this one? looks like the issue maybe related to mono or libmediainfo version in the image. Updating them locally on the machine seems to have no effect. Does anyone know if there is a way to change the version of mono and libmediainfo in the docker image?

**Comment by j0nnymoe** [comment]
@rajivravio Edited your post to removed the filename references for obvious reasons. I would say you need to confirm that your image is up to date and also as sonarr directly if they're able to figure this out any further.
