### ISSUE TITLE
Web Ui not accessible

### ISSUE THREAD

**Issue by vascozorrinho** [linuxserver/docker-sonarr#230]
## Description
Accessing the web ui URL gives me a browser error.

## Expected Behavior
Web UI is visible ans accesible

## Current Behavior
Web UI not accessible

## Steps to Reproduce
1. Open url in browser

## Environment
**OS:**"Raspbian GNU/Linux 10 (buster)
**CPU architecture:** armhf
**How docker service was installed:** Using dockstarter.
**Hardware:** Raspberry Pi 4 4GB

## Docker logs
[Pastebin](https://pastebin.com/DkrYdcNj)

## Notes 
I know that my architecture is not supported but i'm not sure if it is expected to stop working like this. Is there a solution or workaround?

**Comment by thespad** [comment]
Pin to an older tag as per https://info.linuxserver.io/issues/2022-08-02-sonarr/
