### ISSUE TITLE
arm 32bit version

### ISSUE THREAD

**Issue by vlinnie** [linuxserver/docker-sonarr#231]
Why o Why did you remove the 32 bits version, I am using this docker on my raspberry pi and that is only 32bits compatible. please reinclude the armhf please please please!

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

**Comment by Roxedus** [comment]
https://info.linuxserver.io/issues/2022-08-02-sonarr/
Out of our control.

**Comment by vlinnie** [comment]
can't you make an alternative 32bits version alive so at least those people have something to install?

**Comment by vlinnie** [comment]
I will try going for the raspberry pi 64bits lite os. hopefully this will make things work again
