### ISSUE TITLE
Docker fails to start with error: "s6-overlay-suexec: fatal: can only run as pid 1"

### ISSUE THREAD

**Issue by UnconditionalLoop** [linuxserver/docker-sonarr#234]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Docker should start.

## Current Behavior
It doesn't.

## Environment
Linux CoreELEC 4.9.269 #1 SMP PREEMPT Wed Jul 27 09:00:53 CEST 2022 aarch64 GNU/Linux

# FIX
Issue solved by adding following line to docker-compose.yml

init: false

**Comment by aptalca** [comment]
You should set that in your docker system config (or remove the setting that sets it to true).
