### ISSUE TITLE
Develop tag failing to build, error with repo (apt-get update)

### ISSUE THREAD

**Issue by RandomNinjaAtk** [linuxserver/docker-sonarr#237]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Image should build successfully

## Current Behavior
When `apt-get update` is performed, you get the following error:
```
2022-11-11T14:12:03Z #7 3.721 Get:31 http://archive.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [27.5 kB]
2022-11-11T14:12:03Z : The repository 'https://mediaarea.net/repo/deb/ubuntu focal Release' does not have a Release file.
2022-11-11T14:12:03Z ------
```
Docker file for reference: https://github.com/RandomNinjaAtk/docker-sonarr-extended/blob/main/amd64.dockerfile

Looks to be caused by a certificate issue:
```
Err:4 https://mediaarea.net/repo/deb/ubuntu focal Release           
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 45.56.78.187 443]
Get:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
```

## Steps to Reproduce

1. Run sonarr container
2. Perform apt-get update

## Environment
**OS:** Linux (Unraid)
**CPU architecture:** Applicable to all: x86_64/arm32/arm64
**How docker service was installed:**

## Command used to create docker container (run/create/compose/screenshot)
N/A

## Docker logs

Docker Build error (docker hub):
```
2022-11-11T14:12:03Z #7 3.721 Get:31 http://archive.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [27.5 kB]
2022-11-11T14:12:03Z : The repository 'https://mediaarea.net/repo/deb/ubuntu focal Release' does not have a Release file.
2022-11-11T14:12:03Z ------
```
Error in existing container, when attempting to CLI run apt-get update:
```
Err:4 https://mediaarea.net/repo/deb/ubuntu focal Release           
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 45.56.78.187 443]
Get:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
```

**Comment by thespad** [comment]
Looks like a CDN problem, the cert I'm seeing from the UK is perfectly valid:

![Screenshot 2022-11-11 144403](https://user-images.githubusercontent.com/8425502/201363628-f9b296b0-78dd-4bf6-9f51-b23b31d0ce54.png)

But the cert being presented by the US endpoint is expired:

![image](https://user-images.githubusercontent.com/8425502/201363754-3613ee4d-4038-4abc-91d9-27d0b67e8430.png)

**Comment by RandomNinjaAtk** [comment]
This now appears to be resolved
