### ISSUE TITLE
/usr/bin/env: ‘python3’: No such file or directory

### ISSUE THREAD

**Issue by Quiksmage** [linuxserver/docker-sonarr#238]
This appears to be happening both on latest and develop. I'm not sure when it started, but my script no longer runs within sonarr and I get presented with the following error message

"/usr/bin/env: ‘python3’: No such file or directory"

Is there another way I can do this? or a different version of python? Thanks for the help!

**Comment by Roxedus** [comment]
See #216

**Comment by Quiksmage** [comment]
appreciate it!
