### ISSUE TITLE
[BUG] Sonarr v4 does not show anymore on LG tv browser. (2021 model in my case)

### ISSUE THREAD

**Issue by mrmuiz** [linuxserver/docker-sonarr#246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sonarr v4 does not open on LG WebOS webbrowser anymore. It did work before. I dont know since wich version it went wrong.
Only the favicon shows. Screen stays white.
It shows up on all other devices, PC, Phone etc. So nothing is wrong with that.
This version shows up normaly : 3.0.9.1549

### Expected Behavior

Go to sonarr on the LG WebOS  webbrowser and browse sonarr.

### Steps To Reproduce

Install latest develop versions.

### Environment

```markdown
Docker on Synology 7
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - /volume1/docker/sonarrtest:/config
      - /volume1/series:/series
      - /volume1/downloads:/downloads
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1026
      - PGID=100
    ports:
      - 3344:8989
    network_mode: synobridge
    restart: unless-stopped
```

### Container logs

```bash
Dont know where to find this.
```

**Comment by j0nnymoe** [comment]
Nothing to do with us. Report this directly to sonarr.

**Comment by mrmuiz** [comment]
> Nothing to do with us. Report this directly to sonarr.

Oke  sorry.
