### ISSUE TITLE
Sonarr runs in non-production mode, leading to some problems

### ISSUE THREAD

**Issue by tofagerl** [linuxserver/docker-sonarr#25]
No idea why or how to fix. Only found out about it due to this error: 
https://forums.sonarr.tv/t/error-sending-nzb-to-nzbget-update-the-request-url-to-avoid-this-redirect/12055/9

**Comment by sparklyballs** [comment]
i don't know what they mean by running sonarr under /run and i don't have an althub forum account.

**Comment by CHBMB** [comment]
Maybe try without your own tweaks as you mentioned in the thread?

**Comment by tobytl** [comment]
> i don't know what they mean by running sonarr under /run ...

Sonarr has a production environment check, when not in production mode, it will not follow redirects like althub is throwing (http redirecting to https). One of those checks is if the CWD of the activating process is in the /run directory off of root. That check has been eliminated in the develop branch of sonarr it seems, so once that makes it to stable, this problem may go away.

It looks like it may not be the fault of this container directly if this is the problem. I think it's s6. All of the s6-overlay services are being relocated to /run/s6/services/ and run from there (eg: s6-supervise for sonarr has a CWD of "/run/s6/services/sonarr" which contains it's run script and some state info for s6-supervise).

**Comment by tobytl** [comment]
Yea, it looks like it's definitely the CWD issue. Found a quick and dirty fix No idea how s6 does it's thing, or if sub shells screw it up, but basically change the working directory before exec'ing into s6-setuidgid. As such, didn't want to do anything official through github without knowing the repercussions.

Change the line in run to 
`( cd /opt/NzbDrone && XDG_CONFIG_HOME="/config/xdg" exec s6-setuidgid abc mono /opt/NzbDrone/NzbDrone.exe -nobrowser -data=/config )`
