### ISSUE TITLE
[BUG] sonnar no matching manifest for linux arm v9 PI 4 8GB device.

### ISSUE THREAD

**Issue by porrascarlos802018** [linuxserver/docker-sonarr#257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

docker-compose up -d
Pulling sonarr (lscr.io/linuxserver/sonarr:latest)...
latest: Pulling from linuxserver/sonarr
ERROR: no matching manifest for linux/arm/v8 in the manifest list entries

none of these images would work on PI 4 8GB
docker pull linuxserver/sonarr:4.0.0-develop

linuxserver/sonarr
lscr.io/linuxserver/sonarr:latest
ghcr.io/hotio/sonarr:v4-62028b1

### Expected Behavior

to have the container up and running 

### Steps To Reproduce

docker-compose up -d

yaml:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    expose:
      - 8989
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Argentina/Mendoza
    volumes:
      - /media/sonarr:/config
      - /media/tv:/tv
      - /media/downloads/completed:/downloads

### Environment

```markdown
- OS: rasbpbian 64 lite
- How docker service was installed:
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88
echo "deb [arch=armhf] https://download.docker.com/linux/debian \
     $(lsb_release -cs) stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list
sudo apt-get update && sudo apt-get install -y --no-install-recommends docker-ce docker-compose
```

### CPU architecture

arm64

### Docker creation

```bash
docker-compose up -d
```

### Container logs

```bash
none listed.
```

**Comment by aptalca** [comment]
The issue is with your host. If it's a proper rpi4 running 64 bit raspbian, it should request `linux/arm64`, which we publish an image for in the manifest: https://hub.docker.com/r/linuxserver/sonarr/tags

> `echo "deb [arch=armhf] https://download.docker.com/linux/debian \`

It looks like you installed the `armhf` docker repo, which is the 32bit version

**Comment by porrascarlos802018** [comment]
thanks for checking this one, this is what I got from the os:
root@pi4:/home/carlos# uname -a
Linux pi4 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64 GNU/                                                                                        Linux
root@pi4:/home/carlos# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@pi4:/home/carlos#

root@pi4:/home/carlos# uname -m
aarch64

 lshw
pi4
    description: Computer
    product: Raspberry Pi 4 Model B Rev 1.4
    serial: 10000000cbb21722
    width: 64 bits
    capabilities: smp cp15_barrier setend swp tagged_addr_disabled

dpkg --print-architecture
arm64

 arch
aarch64

could it be docker problem?

**Comment by aptalca** [comment]
Follow the uninstall steps outlined in the docker install page. Then reinstall via the convenience script: https://docs.docker.com/engine/install/debian/#install-using-the-convenience-script

**Comment by Xavopls** [comment]
I'm in the exact same scenario, same raspberry, same OS and same error.
I think that this is an error related to how the Sonarr image detects and classifies the architecture, since I have many docker containers that also allow the arm/v8 working correctly, including Radarr.

**Comment by aptalca** [comment]
It has nothing to do with sonarr.

Your docker installs are faulty. You have been (unkowingly) running 32 bit images on your 64 bit devices and OS. Sonarr does not have a 32 bit image published to the hub. That's why you're noticing the issue now.
