### ISSUE TITLE
[FEAT] Add Ping Command to container

### ISSUE THREAD

**Issue by Jo-Dan** [linuxserver/docker-sonarr#259]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Adding the "ping" unix command to the container.

### Reason for change

Most of your other media server containers (e.g. Radarr) have the ping command, but this one doesn't. The ping command is a nice easy way to have a healthcheck for the container being able to connect to a particular website or device.

Would it be possible to add this command in?

**Comment by thespad** [comment]
Ping is a terrible choice for connectivity verification, especially over the internet.

That said if you want to add it to the container you can use our mod https://github.com/linuxserver/docker-mods/tree/universal-package-install - it's not something we'll add to the main image (Alpine-based images get a limited ping tool via busybox, it's not explicitly installed).

**Comment by thespad** [comment]
For most services, curl, for edge cases, UDP etc. then other tools like netcat may be more practical.
