### ISSUE TITLE
[FEAT] ability to modify routing table on startup

### ISSUE THREAD

**Issue by DLV111** [linuxserver/docker-sonarr#271]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Hey Team,

I want the ability to modify the routing table upon startup - I do this with many of your other containers so I can route it via my VPN, but have notced this one is missing the IP package, while I can 100% install it myself, thought i'd ask why this one is missing it but all others have it.

Thanks

### Reason for change

Ability to route container traffic through another container for VPN reasons.

### Proposed code change

add the iproute2 package

**Comment by aptalca** [comment]
Not something we explicitly add, but comes with the base OS. The difference is (I'm guessing) Alpine has it baked in, but Ubuntu does not.

For those instances, we recommend the universal package install mod

**Comment by DLV111** [comment]
Thanks @aptalca, that explains it. I'll checkout the Universal package install mod.
