### ISSUE TITLE
s6-supervise (child): fatal: unable to exec run: Permission denied - On start

### ISSUE THREAD

**Issue by painejake** [linuxserver/docker-sonarr#28]
When starting the container the following errors are outputted into the log:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 
-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \ 
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|
Brought to you by linuxserver.io
We do accept donations at:
https://www.linuxserver.io/donations
-------------------------------------
GID/UID
-------------------------------------
User uid:    1006
User gid:    500
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise sonarr: warning: unable to spawn ./run - waiting 10 seconds
[services.d] done.
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise sonarr: warning: unable to spawn ./run - waiting 10 seconds
```

Running:
CentOS 7 - 3.10.0-327.36.2.el7.x86_64
Docker version 1.10.3, build cb079f6-unsupported

SELinux set to permissive

Command used to created container:
`docker create --name sonarr -p 8989:8989 -e PUID=1006 -e PGID=500 -v /dev/rtc:/dev/rtc:ro -v /home/sonarr:/config -v /home/media:/tv -v /home/sonarr:/downloads linuxserver/sonarr`

Where 1006 is the UID of the sonarr user and 500 is the GUID of the media group (shared between all necessary containers)

Seems that it could be linked to s6-overlay? Not sure only been using docker for a few days :)

Links:
https://github.com/just-containers/s6-overlay/issues/158

Let me know if any further information is required

**Comment by tobbenb** [comment]
Are you using the centos package for docker or the official docker version?
If you use the centos version, please remove it and install the official docker version.

**Comment by painejake** [comment]
Thanks @tobbenb will give that a whirl

**Comment by painejake** [comment]
That's exactly the issue, I didn't even think of installing the latest version from the docker repo!

Thanks

**Comment by Ten-Ten-Steve** [comment]
I'm having this exact same issue on Fedora 25, with the same image. However, switching from the fedora Docker package to the Official Docker package did not resolve this issue for me. Any other suggestions out there?

**Comment by fdrock** [comment]
I am having the same issue under Fedora 25 for 2 different containers, Sonarr and Plex.

> s6-supervise plex: warning: unable to spawn ./run - waiting 10 seconds

> s6-supervise sonarr: warning: unable to spawn ./run - waiting 10 seconds

Any way we can re-open this thread or should we open a new one?

**Comment by sparklyballs** [comment]
it's an issue directly with fedora 25 and docker

https://github.com/just-containers/s6-overlay/issues/158#issuecomment-266913426

there's not much we can do about it until it's fixed upstream by either fedora or docker.

**Comment by inhumantsar** [comment]
@sparklyballs there's a workaround listed in that comment which works. ie: adding `VOLUME ["/run"]` to the dockerfile or `-v /run`.
