### ISSUE TITLE
[BUG] Language selection missing

### ISSUE THREAD

**Issue by Gunsi1973** [linuxserver/docker-sonarr#284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In previous versions it was possible to select the language that you wanted sonarr to look for. In this release the language selection, while adding new shows, is missing. The same does not apply for radarr.  There is also no language selection in quality profiles.

was working in earlier versions of sonarr or the image.

### Expected Behavior

when adding new shows the preferred language should be selectable. 
at the moment the following selections can be made:

- root folder
- monitor
- quality profile
- series type
- season folder (checkmark)
- tags

Language is missing.

### Steps To Reproduce

Docker Environment
lastest image from linuxserver.io

- search for show
- click on show
- new dialog should provide language selection

### Environment

```markdown
- OS:ubuntu 22.04
- How docker service was installed: apt install
```

### CPU architecture

x86-64

### Docker creation

```bash
`---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/data:/config
      - /path/to/tvseries:/tv #optional
      - /path/to/downloadclient-downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped`
```

### Container logs

```bash
no output when adding shows
```

**Comment by thespad** [comment]
https://wiki.servarr.com/sonarr/faq-v4#where-have-language-profiles-gone
