### ISSUE TITLE
ADM v2 Asustor to v3

### ISSUE THREAD

**Issue by Londonsmee** [linuxserver/docker-sonarr#285]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Could you add the v3 or maybe even the v4 beta as the v2 coming to end of life. 

### Reason for change

improved interface, sometimes worth a change. Cant do it personally having additional choose isn't a bad thing

### Proposed code change

dunn hope that covers everthing cheers.

**Comment by thespad** [comment]
We haven't built a Sonarr v2 image in nearly 3 years; we have no control over what Asustor do in terms of surfacing Docker images on their hardware, but all of our images are available on multiple registries to be pulled by docker CLI or compose as per our documentation.
