### ISSUE TITLE
[BUG] Stuck on migrating, keeps trying to boot

### ISSUE THREAD

**Issue by kristianbinau** [linuxserver/docker-sonarr#293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sonarr keeps restarting over and over again, seems to be a problem with the migrations. No actual error tho : /

This is the logs: https://gist.github.com/kristianbinau/c222362ca0b1c5d6a775751980a0350a

### Expected Behavior

That Sonarr starts : )

### Steps To Reproduce

![image](https://github.com/linuxserver/docker-sonarr/assets/53931453/15814f50-d9b1-45fe-97e9-b8f650843b33)

### Environment

```markdown
- OS: 
       Unraid 6.12.10
- How docker service was installed: 
       Through the Community Apps.
       Currently on the latest version of the docker container: https://github.com/linuxserver/docker-sonarr/releases/tag/4.0.4.1491-ls239
```

### CPU architecture

x86-64

### Docker creation

![image](https://github.com/linuxserver/docker-sonarr/assets/53931453/15814f50-d9b1-45fe-97e9-b8f650843b33)

### Container logs

```bash
https://gist.github.com/kristianbinau/c222362ca0b1c5d6a775751980a0350a
```

**Comment by j0nnymoe** [comment]
Corrupted database? Try restoring a backup or test with a fresh appdata folder.

**Comment by kristianbinau** [comment]
It was fixed after yesterdays update. 👍 Pretty sure it was related to: https://github.com/Sonarr/Sonarr/pull/6778
