### ISSUE TITLE
[FEAT] ENV to change default port in config.xml

### ISSUE THREAD

**Issue by MJBgood** [linuxserver/docker-sonarr#301]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I would like to be able to specify the default port in the config.xml when initially running the image. I am not sure if this is an unreasonable ask, apologies if so!

By extension, it would be nice to have ENV for the config.xml as a whole (ssl, ssl port, etc)

### Reason for change

When you run multiple sonarr or radarr instances and change their network mode to use gluetun, the default port conflicts and only one app is accessible. Even changing the name of the duplicates (ie sonarr, sonarr-anime, sonarr-4k) and having a different config directory does not change this. As of right now, you have to run the apps, go to the config directories (aside from the first instance's) and change the port, then rebuild the containers. This is more tedious it seems in TrueNAS Scale 24.10-rc.

**Comment by aptalca** [comment]
You can set up the container without gluetun, change the port, and then put it on the gluetun network.

We have no plans to add an env var for changing the internal port.

**Comment by Roxedus** [comment]
should've checked upstream first. https://wiki.servarr.com/useful-tools#using-environment-variables-for-config
