### ISSUE TITLE
[BUG] Latest dev tagged release seems to be broken - Queue page won't display.

### ISSUE THREAD

**Issue by kmadaras** [linuxserver/docker-sonarr#304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The latest reelase breaks the Queue page.  I swapped it out with the same release from hotio and it works fine.  Looks like perhaps a database transform issue. 

### Expected Behavior

Queue Page Displays

### Steps To Reproduce

Click on Activity, then Qeeue.  Error on the page is can't display queue.

### Environment

```markdown
- OS:Docker on Bookworm
- How docker service was installed: Official Docker Repo, using compose file matching the notes with minor alterations.
```

### CPU architecture

x86-64

### Docker creation

```bash
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=<Redacted>
    volumes:
      - sonarr_config:/config
      - <Redacted>
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      <Redacted>:
        ipv4_address: <Redacted>

networks:
 <Redacted<:
    external: true

volumes:
  <Redacted>:
```

### Container logs

```bash
Lost due to attempts to restore, also lost the trace, yet it was in reference to a database error for the queue.  The downloads were still working, yet the queue page could not be used.  I tried the database restore first, this dodn't fix anything, so I went with a new container downloads, didn't work.  Finally, switched over to hotio, same version, worked.
```

**Comment by Roxedus** [comment]
Would be a upstream issue. maybe https://github.com/Sonarr/Sonarr/issues/7422

**Comment by kmadaras** [comment]
Good call, I didn't find this issue and apologies for my fail, weird thing is the same release works packaged from hotio, so, for now I'll just run that, unfortunately I much prefer the customization of your releases and I'm not sure if it's a safe downgrade.  Appreciate the quick response, seems it's probably upstream and maybe hotio repackaged.
