### ISSUE TITLE
[BUG] Issue with Sonarr and Radarr - Trakt 401 error

### ISSUE THREAD

**Issue by JackobStuard** [linuxserver/docker-sonarr#305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, I have issue with Sonarr and Radarr docker I am using Home Assistent on raspberry pi 4.
So problem is that if I want to connect 'Trakt' import list to Sonarr or Radarr it show me error "401 not autorized"
I think issue is only with home assistent this docker.
Images bellow
![Screenshot 2024-12-08 at 02 33 00](https://github.com/user-attachments/assets/0899ee0c-f42e-4021-a417-290920d217c8)
![Screenshot 2024-12-08 at 02 33 25](https://github.com/user-attachments/assets/29a897be-cdd2-4073-99b4-d1c59daf0f03)
![Screenshot 2024-12-08 at 02 33 36](https://github.com/user-attachments/assets/3c6a152f-9a1a-4b9b-8bbd-12dd85f5baca)
![Screenshot 2024-12-08 at 02 33 40](https://github.com/user-attachments/assets/85a41b0a-d1fa-474f-b043-cd3b1c80aa4a)

### Steps To Reproduce

1. Open sonarr or radarr
2. Go to Settings -> Import Lists
3. Click + button
4. Select 'Trakt List'
5. Scroll down click "Authenticate with Trakt"
6. when  'sign-in' on that platform and click 'yes' it show that 401: Unauthorized

P.S. I think issue with Docker as it dont send back that info from trakt back to docker for some reason?

### Environment

```markdown
- OS: Home assistant, raspberry pi 4, 4GB
- How docker service was installed: HA Add-ons by alexbelgium
```

### CPU architecture

arm64

### Docker creation

```bash
I add from home assistant store "HA Add-ons by alexbelgium"
```

### Container logs

```bash
There is no errors in home assistent for that.
```

**Comment by j0nnymoe** [comment]
You need to seek support from sonarr directly, we support the container, not the app.
