### ISSUE TITLE
[BUG] 4.0.11 (amd64)  won't start, rolling back to 4.0.10 works fine

### ISSUE THREAD

**Issue by Neriderc** [linuxserver/docker-sonarr#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to update to 4.0.11 I get this error:
```
sonarr  | s6-rc-compile: fatal: invalid /etc/s6-overlay/s6-rc.d/init-sonarr-config/type: must be oneshot, longrun, or bundle
```

It does not launch at all, and stops at this point (stays running, but nothing further happens)

### Expected Behavior

When I roll back to 4.0.10 it launches and runs fine.

### Steps To Reproduce

1. In docker compose run with 
```
image: linuxserver/sonarr
```

2. View logs and see
```
sonarr  | s6-rc-compile: fatal: invalid /etc/s6-overlay/s6-rc.d/init-sonarr-config/type: must be oneshot, longrun, or bundle
```
3. Change image to the following then run:
```
image: linuxserver/sonarr:4.0.10
```
4. See that it starts up fine

### Environment

```markdown
- OS:Linux Mint 21
- How docker service was installed: From docker repo
```

### CPU architecture

x86-64

### Docker creation

```bash
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - ./sonarr_config:/config
      - /mnt/Data/Media/TV:/tvshows
      - /mnt/Data/Media/transmission/downloads/complete:/downloads/complete
```

### Container logs

```bash
sonarr  | s6-rc-compile: fatal: invalid /etc/s6-overlay/s6-rc.d/init-sonarr-config/type: must be oneshot, longrun, or bundle
```

**Comment by Roxedus** [comment]
Delete the image on your host, and re-pull

**Comment by Neriderc** [comment]
That worked, thanks!
