### ISSUE TITLE
synology specific setup

### ISSUE THREAD

**Issue by er0ck** [linuxserver/docker-sonarr#31]
container starts up successfully but doesn't really *do* anything:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
stdout
17:59:44
[s6-init] ensuring user provided files have correct perms...exited 0.
stdout
17:59:44
[fix-attrs.d] applying ownership &amp; permissions fixes...
stdout
17:59:44
[fix-attrs.d] done.
stdout
17:59:44
[cont-init.d] executing container initialization scripts...
stdout
17:59:44
[cont-init.d] 10-adduser: executing... 
stdout
17:59:45
usermod: no changes
stdout
17:59:45
stdout
17:59:45
-------------------------------------
stdout
17:59:45
          _     _ _
stdout
17:59:45
         | |___| (_) ___
stdout
17:59:45
         | / __| | |/ _ \ 
stdout
17:59:45
         | \__ \ | | (_) |
stdout
17:59:45
         |_|___/ |_|\___/
stdout
17:59:45
               |_|
stdout
17:59:45
stdout
17:59:45
Brought to you by linuxserver.io
stdout
17:59:45
We gratefully accept donations at:
stdout
17:59:45
https://www.linuxserver.io/donations/
stdout
17:59:45
-------------------------------------
stdout
17:59:45
GID/UID
stdout
17:59:45
-------------------------------------
stdout
17:59:45
User uid:    911
stdout
17:59:45
User gid:    911
stdout
17:59:45
-------------------------------------
stdout
17:59:45
stdout
17:59:45
[cont-init.d] 10-adduser: exited 0.
stdout
17:59:45
[cont-init.d] 30-config: executing... 
stdout
17:59:45
[cont-init.d] 30-config: exited 0.
stdout
17:59:45
[cont-init.d] done.
stdout
17:59:45
[services.d] starting services
stdout
17:59:45
[services.d] done.
```

the host/port says:
```
Error response

Error code: 501

Message: Unsupported method ('GET').

Error code explanation: HTTPStatus.NOT_IMPLEMENTED - Server does not support this operation.
```

i can see `mono nzbdrone <blah>` running in the process list via the terminal on the container

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

synology DSM 6

we have `/config` `/tv` `downloads` mounted

**Comment by sparklyballs** [comment]
where are you seeing this error, in your browser ?

**Comment by er0ck** [comment]
the 501?  yes

**Comment by sparklyballs** [comment]
you need to be using the ip address of your synology 
so if it's `192.168.1.1` for instance, then you should be using `192.168.1.1:8989`

also you haven't set the PGID and PUID variables

**Comment by er0ck** [comment]
yep.  i've tried using bridged networking, shared host networking, i've tried setting PGID and PUID env vars to root (0), and running with and without high privilege.
the only difference i see in the log is sometimes it says, repeatedly:
`Press enter to exit...`

**Comment by sparklyballs** [comment]
it's something specific to you or the synology

can you post whatever a screenshot of whatever it is you use in synology to configure this docker

**Comment by er0ck** [comment]
what type of information do you need?  there are about 5-6 screens in configuring the launch of a container.  i could try just launching it at the CLI i suppose.
but basically there are screens for setting bridge or host networking, mounting volumes, mapping ports, and setting env vars

**Comment by er0ck** [comment]
if i create/start from the CLI:
```
sh-4.3# docker create --name sonarr -p 8989:8989 -e PUID=0 -e PGID=0 -v /dev/rtc0:/dev/rtc:ro -v /volume1/docker/sonarr/config/ -v /volume1/video/tv/:/tv -v /volume1/docker/sabnzbd/config/Downloads/complete/tv/:/downloads linuxserver/sonarr
6c401f85a29f9c0b0e82510fbb169f51d6ed789f2825f604ffc18f2efe849c28
sh-4.3# docker start sonarr
Error response from daemon: driver failed programming external connectivity on endpoint sonarr (2a232a3da33bec18cc8b2be4f828b27cf72d53217cc052b225a3fe3ee67e5c65): Error starting userland proxy: listen tcp 0.0.0.0:8989: bind: address already in use
Error: failed to start containers: sonarr
```

i don't currently have any other sonarr containers existing, and none running.  i also rebooted the nas, and it still thinks the port is taken.
![headscratch](http://1.bp.blogspot.com/-qMum87QSBbU/UovfxJ14woI/AAAAAAAARpA/W75dpzxNDUE/s1600/Scratching+Head.jpg)

**Comment by er0ck** [comment]
if i change the port to 8990 in config.xml and re create the container mapping that port, it starts.  same log as OP, without the `press enter` thing.
but the service on 8990 gives and empty response. 
`ERR_EMPTY_RESPONSE`
and after a little while no reply at all.

**Comment by zaggash** [comment]
There might be an application listening on 8989. Try something like - p
8990:8989 this will bind the application on port  8990 on your nas.

**Comment by er0ck** [comment]
thanks for the reply @zaggash, i tried exactly that. 
it gave me a similar response.  it's strange that when i create the container with the UI i can start against port 8989 just fine :woman_shrugging:

**Comment by er0ck** [comment]
still having issues.  other linuxserver supported containers work as i'd expect

**Comment by DracoMilesX** [comment]
`docker create --name sonarr -p 8989:8989 -e PUID=0 -e PGID=0 -v /dev/rtc0:/dev/rtc:ro **-v /volume1/docker/sonarr/config/** -v /volume1/video/tv/:/tv -v /volume1/docker/sabnzbd/config/Downloads/complete/tv/:/downloads linuxserver/sonarr`

Your first issue might be related by the fact that the config isn't mapped.

This is mine running Xpenology DSM 6:

`docker run -d \
    --name sonarr \
    --memory=256M \
    --memory-swap=384M \
    -p 18200:8989 \
    -v /dev/rtc0:/dev/rtc:ro \
    -v /volume4/Drive4/Apps/sonarr:/config \
    -v /volume1/Drive/Shows:/tv \
    -v /volume1/Drive:/volume1/Drive \
    -v /volume3/Drive3:/volume3/Drive3 \
    -v /volume1/Drive/Downloads:/downloads \
    linuxserver/sonarr`

**Comment by j0nnymoe** [comment]
Checking in to see if this is still an issue? If not, I will close this issue.

From what I can tell, is you need to setup a value other than root when setting up the containers, We don't recommend running them as root. http://drfrankenstein.co.uk/2016/03/29/setting-up-sonarr-in-docker-on-a-synology-nas/ will help you.

**Comment by er0ck** [comment]
still an issue.  i haven't been able to get back to this.

**Comment by j0nnymoe** [comment]
@er0ck ok, well for now, I am going to close this issue and suggest you follow the guide I linked for setting up sonarr on a syno device. If after trying a fresh install with that you are still having issues, you can reopen this issue but unfortunately no one within the team owns any syno hardware so unable to do any testing/etc with this.
