### ISSUE TITLE
[BUG] no matching manifest for linux/arm/v8 in the manifest list entries

### ISSUE THREAD

**Issue by penggongkui-job** [linuxserver/docker-sonarr#310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

docker pull linuxserver/sonarr:arm64v8-develop
it tell me the follow error:
no matching manifest for linux/arm/v8 in the manifest list entries

### Steps To Reproduce

docker pull linuxserver/sonarr:arm64v8-develop on a 32bit device(my device is coreelec os)

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

arm64

### Docker creation

```bash
none
```

### Container logs

```bash
no matching manifest for linux/arm/v8 in the manifest list entries
```

**Comment by Roxedus** [comment]
We do not publish arm32 images. If your device is 64bit, you should have a 64bit OS.
https://www.linuxserver.io/blog/end-of-an-arch

**Comment by penggongkui-job** [comment]
@Roxedus I cannot upgrade to 64bit OS, the coreelec is not support with my device with 64bit os

**Comment by penggongkui-job** [comment]
I am not need the 32bit images, just arm64/v8 , like the jellyfin/jellyfin docker images:

**Comment by penggongkui-job** [comment]
CoreELEC:~ # docker version
Client:
 Version:           26.0.2
 API version:       1.45
 Go version:        go1.22.2
 Git commit:        3c863ff8d3f0b81f25ed3afb60f2822019c4b94f
 Built:             Wed May  1 02:28:40 UTC 2024
 OS/Arch:           linux/arm
 Context:           default

Server:
 Engine:
  Version:          library-import
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.22.2
  Git commit:       library-import
  Built:            library-import
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.7.15
  GitCommit:        926c9586fe4a6236699318391cd44976a98e31f1
 runc:
  Version:          1.1.12
  GitCommit:        51d5e94601ceffbbd85688df1c928ecccbfa4685
 docker-init:
  Version:          0.19.0
  GitCommit:
CoreELEC:~ # uname -a
Linux CoreELEC 4.9.269 #1 SMP PREEMPT Mon Aug 26 17:08:18 CEST 2024 aarch64 GNU/Linux

this is my system info and docker info

**Comment by j0nnymoe** [comment]
You can't run those images as your OS clearly states "OS/Arch: linux/arm"

**Comment by penggongkui-job** [comment]
yeah, i cannot, so is it possible to add back the arm64/v8 image back, i can use that image

**Comment by j0nnymoe** [comment]
If you look, we have those images. Your issue is your host OS.

**Comment by penggongkui-job** [comment]
i need a image with variant is v8, just like the jellyfin

```
docker manifest inspect jellyfin/jellyfin
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1999,
         "digest": "sha256:040461da121ebe7f5055a385d0f1fc8e8260509041ff0fbce54ec52da2b6bf60",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2002,
         "digest": "sha256:5820494c52b371ab91cbf4732d1632686bf0b87c7639cdbfcba23a4a443ca45a",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1996,
         "digest": "sha256:8d6a97e97d28298789fc6f997760a2ed5959d4136f61ba13667167fe5d41611b",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      }
   ]
}
```

**Comment by penggongkui-job** [comment]
I think it will not take too much time add this, maybe just docker build with another param?

**Comment by thespad** [comment]
We know what you need, which is a 32-bit image, and we haven't published 32-bit images in nearly a year now, as per https://www.linuxserver.io/armhf

For all of the reasons stated there we will not be reintroducing 32-bit images for any of the containers we support.

**Comment by penggongkui-job** [comment]
> You may also have a 64-bit kernel with a 32-bit userspace, especially if you're running an OS like LibreELEC or OSMC, which likely means a 32-bit Docker install. Running getconf LONG_BIT will give you a response of 32 if this is the case.

where should i run this command?

**Comment by j0nnymoe** [comment]
On the host via CLI/SSH.

**Comment by penggongkui-job** [comment]
Yes, I am this case, so there is not workaround to use the docker image?

**Comment by j0nnymoe** [comment]
The work around is to install a 64bit OS.
