### ISSUE TITLE
Import failed, path does not exist or is not accessible by Sonarr: /data/completed/tv-show-name

### ISSUE THREAD

**Issue by dccxxvi** [linuxserver/docker-sonarr#39]
i installed transmission and sonarr via docker container. sonarr scans and finds the right show. it sends it to transmission but here is the problem.

from sonarr logs 
Component - DownloadEpisodesImportService
Message - Import failed, path does not exist or is not accessible by Sonarr: /data/completed/tv-show-name

the "completed" folder is owned by the same user as the PUID and PGID (not owned by root) but it just wont move. I have tried to give other users full RW for this folder but still no good.

any advice is greatly appreciated.

http://imgur.com/a/Tlhh8
http://imgur.com/a/sZgaz

containers i am using
https://github.com/haugene/docker-transmission-openvpn
https://hub.docker.com/r/linuxserver/sonarr/

**Comment by aptalca** [comment]
The mount paths don't match for the two containers.

Transmission tells sonarr that the files are located at /data/completed, however sonarr doesn't even have a mountpoint called /data so it cannot find the files at that location. Change one of the container's mount path for the download location to match the other

**Comment by dccxxvi** [comment]
Hi,

If you take a look at this image
http://imgur.com/a/Tlhh8

Transmission volume set up is folder /docker for mount path /data
Sonarr is set up for /docker/completed

http://imgur.com/a/sZgaz
this shows that the completed downloads goes into /data/completed which is really /docker/completed

shouldnt that be correct? there technically isnt a "data" folder. its both pointing at the "docker" folder. thats my understanding at least

**Comment by CHBMB** [comment]
Make both have a folder mapped to `/downloads` within the container and '/whatever/host/folder/you/want/' exactly the same for both containers and then set them both up within the webui.  This is a config issue, this fix will work.

**Comment by madvtak** [comment]
@CHBMB I'm sorry to have bumped this but can you explain this a bit more. I feel like a 5 year old. This is how I have it set up.

![SAB](https://user-images.githubusercontent.com/18261123/28954181-1fa3d83e-7892-11e7-9955-0944797bf592.png)

![Sonarr](https://user-images.githubusercontent.com/18261123/28954215-79187208-7892-11e7-8dc0-47c9d06aba33.png)
