### ISSUE TITLE
Import failed, path does not exist or is not accessible by Sonarr: /data/completed/tv-show-name #39

### ISSUE THREAD

**Issue by dccxxvi** [linuxserver/docker-sonarr#40]
i installed transmission and sonarr via docker container. sonarr scans and finds the right show. it sends it to transmission but here is the problem.

from sonarr logs
Component - DownloadEpisodesImportService
Message - Import failed, path does not exist or is not accessible by Sonarr: /data/completed/tv-show-name

the "completed" folder is owned by the same user as the PUID and PGID (not owned by root) but it just wont move. I have tried to give other users full RW for this folder but still no good.

any advice is greatly appreciated.

http://imgur.com/a/Tlhh8
http://imgur.com/a/sZgaz

containers i am using
https://github.com/haugene/docker-transmission-openvpn
https://hub.docker.com/r/linuxserver/sonarr/

If you take a look at this image
http://imgur.com/a/Tlhh8

Transmission volume set up is folder /docker for mount path /data
Sonarr is set up for /docker/completed

http://imgur.com/a/sZgaz
this shows that the completed downloads goes into /data/completed which is really /docker/completed

shouldnt that be correct? there technically isnt a "data" folder. its both pointing at the "docker" folder. thats my understanding at least

**Comment by CHBMB** [comment]
Duplicate issue, I've already responded to your last one.  This isn't an issue with the container it's your config.
