### ISSUE TITLE
Does this work with a proxy (nginx) behind a vpn)?

### ISSUE THREAD

**Issue by jrac86** [linuxserver/docker-sonarr#42]
I have a sonarr container setup behind a vpn container. I am using nginx container in order to access sonarr's web management from outside the vpn. However, it seems I only get to a blank page with this text on the top... 

Sonarr Ver.

So it seems as though Sonarr is running and that nginx is working correctly, but that sonarr does not want to load the full management page. 

My sonarr logs:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1001
User gid:    1001
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Bootstrap: Starting Sonarr - /opt/NzbDrone/NzbDrone.exe - Version 2.0.0.4645
[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Info] MigrationLogger: *** Migrating data source=/config/nzbdrone.db;cache size=-10485760;
[Info] MigrationLogger: *** Migrating data source=/config/logs.db;cache size=-10485760;date
[Info] Router: Application mode: Interactive
[Info] OwinHostController: Listening on the following URLs:
[Info] OwinHostController:   http://*:8989/
[Info] NancyBootstrapper: Starting Web Server
[Error] TaskExtensions: Task Error

[v2.0.0.4645] System.Net.WebException: Error: NameResolutionFailure
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) <0x418f0e10 + 0x00
  at System.Net.HttpWebRequest.GetResponse () <0x418e9ec0 + 0x0005a> in <filename unknown>:
  at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Ht
e.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:63

[Info] RssSyncService: Starting RSS Sync
[Warn] FetchAndParseRssService: No available indexers. check your configuration.
[Info] DownloadDecisionMaker: No results found
[Info] RssSyncService: RSS Sync Completed. Reports found: 0, Reports grabbed: 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1001
User gid:    1001
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Bootstrap: Starting Sonarr - /opt/NzbDrone/NzbDrone.exe - Version 2.0.0.4645
[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Info] MigrationLogger: *** Migrating data source=/config/nzbdrone.db;cache size=-10485760;
[Info] MigrationLogger: *** Migrating data source=/config/logs.db;cache size=-10485760;date
[Info] Router: Application mode: Interactive
[Info] OwinHostController: Listening on the following URLs:
[Info] OwinHostController:   http://*:8989/
[Info] NancyBootstrapper: Starting Web Server
[Error] TaskExtensions: Task Error

[v2.0.0.4645] System.Net.WebException: Error: NameResolutionFailure
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) <0x421fc640 + 0x00
  at System.Net.HttpWebRequest.GetResponse () <0x421f6560 + 0x0005a> in <filename unknown>:
  at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Ht
e.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:63

[Info] RssSyncService: Starting RSS Sync
[Warn] FetchAndParseRssService: No available indexers. check your configuration.
[Info] DownloadDecisionMaker: No results found
[Info] RssSyncService: RSS Sync Completed. Reports found: 0, Reports grabbed: 0
[Info] RssSyncService: Starting RSS Sync
[Warn] FetchAndParseRssService: No available indexers. check your configuration.
[Info] DownloadDecisionMaker: No results found
[Info] RssSyncService: RSS Sync Completed. Reports found: 0, Reports grabbed: 0

**Comment by CHBMB** [comment]
It certainly works behind a proxy.  I reverse proxy this with our letsencrypt container, I also can access it with a VPN connection so I think it must be how you have it configured.

**Comment by j0nnymoe** [comment]
@jrac86 base url been changed?

**Comment by jrac86** [comment]
just to elaborate on my setup, I am using docker containers for sonarr and sabnzbd as well as a container for an openVPN client and nginx for access to the web management pages of sonarr and sabnzbd. I got everything working with Sabnzbd, but sonarr's page wont load. 

Nginx is making it so that hitting the url http:localhost/sonarr will direct to the IP of the sonarr container with the VPN ip. I have not made any changes to Sonarr so the default url should still be used inside the Sonarr container with the VPN. I feel like there is some sort of dependency that Sonarr might need and that is why the site isn't fully loading. 

I am up for suggestions for alternatives to this setup. I just want Sonarr and sabnzbd behind a vpn, but still allow me to hit the web management for each outside of the VPN on my host's local network. I thought docker would be the best utility, as I could have everything on my one PC while taking up minimal resources. I also considered setting up a Linux VM, but I had gotten this far with the docker setup and this seems to be the final issue.  

@CHBMB What containers are you using and how difficult is the setup? I had been using the following containers:

linuxserver/sabnzbd
linuxserver/sonarr
dperson/nginx
dperson/openvpn-client

**Comment by aptalca** [comment]
Without nginx, can you just browse to the machine's ip at the sonarr port and access the sonarr page? 

If so, this has nothing to do with Sonarr. It's about your nginx and openvpn config

**Comment by jrac86** [comment]
I can get to sonarr without the VPN/nginx. I have sabnzbd working with the VPN and nginx, but setting up sonarr with the same method doesn't work. It is possible I set up something wrong, but it looks like it is hitting the sonarr container and just not fully loading it and instead displaying the following on a white page: Sonarr Ver.

**Comment by CHBMB** [comment]
I use a VPN client on my firewall, so slightly different.  To be honest, this isn't an issue with our container but something with your setup as aptalca says.  

Probably better asked on dperson's github as it's to do with how his/her container works.

**Comment by jrac86** [comment]
Okay I have asked dperson as well. I know that the nginx container alters the host file. I read somewhere while searching that sonarr does not like an edited hosts file - does anyone know if that is true?

**Comment by CHBMB** [comment]
No idea.
