### ISSUE TITLE
Permission issues

### ISSUE THREAD

**Issue by matthewdias** [linuxserver/docker-sonarr#52]
I've set the user and group ids to the owner of the directories where the volumes are pointed to, but I'm getting `System.UnauthorizedAccessException: Access to the path "/config/nzbdrone.pid" is denied.`

Host: macOS
run command:
```
docker run --privileged -d
-v /Users/Matthew/Downloads:/data
-v /Users/Matthew/Documents/NzbDrone:/config
-v /Users/Matthew/Anime:/Anime
-v /Users/Matthew/TV:/TV
-e PUID=501 -e PGID=20
--name sonarr -p 8989:8989 --restart always -P linuxserver/sonarr:develop
```

**Comment by DanielArndt** [comment]
I keep running into permission issues as well. I haven't had time to dig deaper into it yet, but it seems like the container is swapping my user id and group id at some point (ie. files are being written as owned by user PGID, and group PUID)

I'm not sure if this is at all related, but thought I'd throw it out there in case it helps you investigate.

**Comment by PHLAK** [comment]
I also just tried to spin up an image with PUID and PGID set and am getting the same errors.

**Comment by DanielArndt** [comment]
My issue was nothing to do with this docker container, so consider the above comment irrelevant. Another container was interfering and messing with the permissions.

**Comment by j0nnymoe** [comment]
@matthewdias still getting these issues?

**Comment by matthewdias** [comment]
I haven't tried recently. Have just been running Sonarr outside of Docker.

**Comment by j0nnymoe** [comment]
ah ok - are you happy for me to close this? or do you want to try and find a solution to the issue?
I personally think it might be something funky that docker for macOS does.

**Comment by matthewdias** [comment]
I'll go ahead and close it. Gonna try to get this working again eventually so if I'm still having the issue then will reopen.

**Comment by j0nnymoe** [comment]
ok no problem :)
