### ISSUE TITLE
Segmentation fault immediately upon startup

### ISSUE THREAD

**Issue by mihalski** [linuxserver/docker-sonarr#53]
Alpine Linux v3.5.2

docker run -d --name sonarr -p 8989:8989 -v /etc/localtime:/etc/localtime:ro -v /docker/sonarr/config:/config -v /docker/sonarr/tv:/tv -v /docker/sonarr/downloads:/downloads linuxserver/sonarr

```
docker log sonarr
docker: 'log' is not a docker command.
See 'docker --help'.
dock:/docker/sonarr/config# docker logs sonarr
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \ 
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```
If I go inside the container and try to run sonarr from the command line I get this:
```
root@2dbbf36e895b:/opt/NzbDrone# s6-setuidgid abc mono --debug NzbDrone.exe -nobrowser -data=/config
Segmentation fault
```
About to get radarr to see if I have the same problem.

EDIT: The radarr container suffers from exactly the same problem.

**Comment by sparklyballs** [comment]
you can't run two instances of sonarr or radarr at the same time in the same container, so i would absolutely expect an error trying to manually run them from the exec line of a running container.

i'm not sure what your issue is.

**Comment by mihalski** [comment]
I can't run ANY instances of sonarr or radarr in a container.

**Comment by sparklyballs** [comment]
not from the command line, that is not the method of running them.

**Comment by mihalski** [comment]
```
dock:~# docker run -d --name sonarr -p 8989:8989 -v /etc/localtime:/etc/localtim
e:ro -v /docker/sonarr/config:/config -v /docker/sonarr/tv:/tv -v /docker/sonarr
/downloads:/downloads linuxserver/sonarr
f97a636ae234e85dac11b883fa94393013726927105d5d78a10814aaf2dc8170
dock:~# docker logs sonarr
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \ 
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
dock:~# docker exec -it sonarr /bin/bash
root@f97a636ae234:/# ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root       282  0.5  0.0  19904  3724 ?        Ss   17:05   0:00 /bin/bash
root       308  0.0  0.0  36084  3348 ?        R+   17:05   0:00 ps -aux
root@f97a636ae234:/# 
```

**Comment by mihalski** [comment]
Shouldn't a process for sonarr show up? Because there is nothing available on the specified port in the web interface.

**Comment by sparklyballs** [comment]
try running it like this with no volumes mounted, first making sure any previous instances aren't running

`docker run -d --name=test --net=host linuxserver/sonarr`

then exec in and run the ps again

**Comment by mihalski** [comment]
Nothing.. But it seems that this is a bad test. It seems that none of the containers on this machine have any processes running and yet all the others work.. I don't know how to explain that.

**Comment by sparklyballs** [comment]
other machines ?

it's a test to see if the mounted volumes are an issue.

**Comment by mihalski** [comment]
The only other docker I have is built on top of resinos and running on a raspberrypi3 so I can't really test using that.

SHOULD I be seeing processes? Is there something else I can try to isolate the problem?

**Comment by sparklyballs** [comment]
`docker run -d --net=host --name=test linuxserver/couchpotato`

and exec in to that one and ps

**Comment by mihalski** [comment]
Nothing. Just like all the other containers on this server, including all the working ones.
```
dock:~# docker run -d --net=host --name=test linuxserver/couchpotato
Unable to find image 'linuxserver/couchpotato:latest' locally
latest: Pulling from linuxserver/couchpotato
bf1e18a82976: Pull complete 
21a6b53d45de: Pull complete 
4211b7ad5f46: Pull complete 
ff16e687cd03: Pull complete 
c9b96d021d25: Pull complete 
dd15e48d328b: Pull complete 
Digest: sha256:24aa448b40a402bf642dcba39cd5174a2ac497397eae11770b117d974fce6b8b
Status: Downloaded newer image for linuxserver/couchpotato:latest
d50128c99df65a32f25a5659ddf46a7f5c5b37fdecb5666f3152b3f440795b1e
dock:~# docker exec -it test /bin/bash
root@dock:/app/couchpotato$ ps
PID   USER     TIME   COMMAND
  185 root       0:00 /bin/bash
  192 root       0:00 ps
```

**Comment by sparklyballs** [comment]
any webui on port 5050 ?

**Comment by mihalski** [comment]
I was about to add.. Couchpotato is available on port 5050 of the host.

**Comment by j0nnymoe** [comment]
I'm confused with the setup of your environment. Could you clarify please what Host OS you are trying to run this on and also what platform? (x86/armhf etc) Thanks

**Comment by mihalski** [comment]
Docker running on KVM based virtual machine running Alpine Linux:
   Linux dock 4.4.59-0-virtgrsec #1-Alpine SMP Tue Apr 4 08:37:50 GMT 2017 x86_64 Linux
Inside of Proxmox virtual environment based on Debian Linux:
   Linux pve 4.4.35-1-pve #1 SMP Fri Dec 9 11:09:55 CET 2016 x86_64 GNU/Linux.

**Comment by mihalski** [comment]
Here's an example of this inside a working nzbget container:
```
dock:~# docker exec -it nzbget /bin/bash
root@7e6fcbdef73d:/$ ps
PID   USER     TIME   COMMAND
  270 root       0:00 /bin/bash
  278 root       0:00 ps
root@7e6fcbdef73d:/$ su
root@7e6fcbdef73d:/$ ps
PID   USER     TIME   COMMAND
  270 root       0:00 /bin/bash
  282 root       0:00 su
  283 root       0:00 ash
  287 root       0:00 ps
```
That just doesn't make sense to me.

**Comment by mihalski** [comment]
Created a Debian Jessie VM. Exactly the same problem. The RECOMMENDED way of running docker on a virtual machine is exactly how I am doing it. I don't understand why this is happening.. and at this stage I can't even begin to dream of what to try next.

**Comment by j0nnymoe** [comment]
whats the full docker create command you are running? 
Also, have you managed to get any of our containers to work?

**Comment by mihalski** [comment]
```
docker run -d --name sonarr -p 8989:8989 -v /etc/localtime:/etc/localtim
e:ro -v /docker/sonarr/config:/config -v /docker/sonarr/tv:/tv -v /docker/sonarr
/downloads:/downloads linuxserver/sonarr
```
Only the sonarr/radarr containers are not "working", the transmission and nzbget ones are working.
None of them (including containers from other sources) show any processes running when the ps command is used from within.

**Comment by mihalski** [comment]
I THINK I've just gotten it to work on the Debian Jessie based docker host.. Still working on it.

**Comment by mihalski** [comment]
I can confirm that Alpine Linux with their provided docker seems to the the problem. On Debian 8 I get the following result:
```
sudo docker exec -it sonarr /bin/bash
root@c680f7f32ca7:/# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0    196     4 ?        Ss   15:20   0:00 s6-svscan -t0 /
root        29  0.0  0.0    196     4 ?        S    15:20   0:00 s6-supervise s6
root       194  0.0  0.0    196     4 ?        S    15:20   0:00 s6-supervise so
abc        197  2.5  3.9 1151780 156812 ?      Ssl  15:20   0:21 mono --debug Nz
root       246  1.0  0.0  19912  3652 ?        Ss   15:34   0:00 /bin/bash
root       255  0.0  0.0  36084  3220 ?        R+   15:34   0:00 ps aux
```
And of course it also works as intended.

Thank you for your help trying to solve this.
Regards,
Michal

**Comment by sparklyballs** [comment]
i'm gonna close this is as being a vagary of alpine linux as host.

**Comment by benjaminabbitt** [comment]
Just wanted to add that this problem still exists as of tag 92.

**Comment by CHBMB** [comment]
@benjaminabbitt You using Alpine Linux as a host?

**Comment by alazare619** [comment]
I can confirm this as well.
Container is running ps exec /bin/bash into it
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \ 
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    0
User gid:    0
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \ 
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    0
User gid:    0
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.`

Ports are exposted to the docker host (alpine linux) other containers are fine just appears to be mono applications that have the issue...I would not close this so fast as docker is bleeding edge on alpine close to archlinux bleeding edge so its likely this is a bug with docker itself

**Comment by alazare619** [comment]
@mihalski @benjaminabbitt  which alpine variants were you using? Did you get the vanilla iso the one without the grsec patches after some further investigation I was finding grsec patches were potentially causing issues with mono based i tested emby,jacket,sonarr,radarr, all seg faulted. I havent tested the vanilla yet but thats my next go to.

**Comment by benjaminabbitt** [comment]
Was using alpine extended build with default options.  I honestly don't recall the kernel version in use (whatever was default + ZFS + Docker)

**Comment by alazare619** [comment]
If you wana give it a go again use the vanilla the one without grsec patches sonarr,radarr all mono apps work perfectly in that version. grsec is like alpines version (essentially) of selinux

**Comment by benjaminabbitt** [comment]
I switched to Arch for now.  May switch back at some point in the future.
Thanks for taking a look at it.

**Comment by javydekoning** [comment]
Came here to state that I have the same issue with Sonarr and Radarr on Alpine. 

```
alpine:/srv/docker/sonarr# uname -a
Linux alpine 4.9.65-1-virthardened #2-Alpine SMP Mon Nov 27 15:53:30 GMT 2017 x86_64 Linux
```

**Comment by alazare619** [comment]
Make sure you use vanilla and not virtual...virtual version of alpine has the grsec patches this will not be fixed as all mono apps with grsec patches will seg fault.

**Comment by javydekoning** [comment]
Thanks, it works well with the vanilla version.

**Comment by cjbottaro** [comment]
```
sysctl -w kernel.pax.softmode=1
```
You're welcome.

**Comment by maur8ino** [comment]
@cjbottaro thank for the tip! 😄
