### ISSUE TITLE
Run Sonarr on privileged ports

### ISSUE THREAD

**Issue by a3rosol** [linuxserver/docker-sonarr#56]
Hi! 

I've recently tried to run sonarr on port 80, but it throws an error because 

> [Fatal] ConsoleApp: Access denied. This can happen if another instance of Sonarr is already running another application is using the same port (default: 8989) or the user has insufficient permissions 

I suspect user abc does not have sufficient permissions. How can I run this as root or use the privileged ports?

**Comment by aptalca** [comment]
Are you trying to change the port in sonarr gui? You're not supposed to do that. Just map port 80 to 8989 in the docker run/create command as `-p 80:8989`

**Comment by a3rosol** [comment]
Yes, indeed. But I want to do that, why isn't this possible?
The -p flag does not work in custom docker networks like macvlan. Can you provide a different way to achieve this?

**Comment by aptalca** [comment]
You can use the nginx/letsencrypt reverse proxy

**Comment by a3rosol** [comment]
That's not really an option for me though. Is there any way, this can be done?

**Comment by aptalca** [comment]
You can set puid and pgid to 0 to run as root but we won't support it
