### ISSUE TITLE
Cant get any other path but /app/

### ISSUE THREAD

**Issue by aprillia99** [linuxserver/docker-sonarr#57]
Is there a way to give sonarr the ability to see the files on my Synology drive? right now it only shows /app/ a lot of other folders but all lead to nothing. I'm downloading shows and saving them to a folder marked media, but sonarr doesn't seem them as downloaded. 

thanks

**Comment by CHBMB** [comment]
Map /media to wherever that is on your host.

**Comment by aprillia99** [comment]
Thanks, took me awhile when its right in front of your face.
