### ISSUE TITLE
[Fatal] ConsoleApp: Access denied. This can happen if another instance of Sonarr is already running another application is using the same port (default: 8989) or the user has insufficient permissions 

### ISSUE THREAD

**Issue by GrumpyMeow** [linuxserver/docker-sonarr#61]
On a regular basis the Sonarr docker container becomes unresponsive. I'm pretty sure it has got to do with me using "Overwatch" to automatically update the Sonarr docker container.

In the log i see this error message:
> [Fatal] ConsoleApp: Access denied. This can happen if another instance of Sonarr is already running another application is using the same port (default: 8989) or the user has insufficient permissions 

In the config.xml of Sonarr i've changed the UI port to "80". As this config file is on a mapped volume, it survives the update and restart done by Overwatch. 

I suspect that upon restarting some process tries to connect to another process on port 8989, but that process is correctly listening on port 80 as i configured this. 

Can somebody confirm this?

**Comment by j0nnymoe** [comment]
No idea what overwatch is but it sounds like its trying to boot the new container while the old one is still running.
