### ISSUE TITLE
Error: MediaInfo Library could not be loaded libmediainfo.so.0 in newest Sonarr Docker build

### ISSUE THREAD

**Issue by luvablemarmot** [linuxserver/docker-sonarr#67]
With latest build of Sonarr with Synology docker Sonarr is displaying the following error:

Error: MediaInfo Library could not be loaded libmediainfo.so.0

Issue did not exist in in previous build.

Synology DSM 6.2
root@filer02:/var/log/Docker# docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.8
 Git commit:   9f07f0e-synology
 Built:        Fri Jan 26 15:43:23 2018
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.8
 Git commit:   9f07f0e-synology
 Built:        Fri Jan 26 15:43:23 2018
 OS/Arch:      linux/amd64
 Experimental: false

No symlinks on mounts.

Have deleted and redeployed container a few times and can reproduce.

**Comment by sparklyballs** [comment]
@luvablemarmot can you screenshot or paste the error so can verify the correct file that may need to be symlinked

**Comment by luvablemarmot** [comment]
![screen shot 2018-04-02 at 4 33 14 pm](https://user-images.githubusercontent.com/2404962/38214760-9f7c3f8c-3693-11e8-93bb-9c294acee40c.png)

What happens with this 'error' is all post processing is halted and files need to be manually imported.

**Comment by captn3m0** [comment]
Are you on the `develop` tag by any chance? I'm using `sonarr:latest` and don't get the same error.

```
 docker version
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.10
 Git commit:	0520e24302
 Built:	Fri Mar 23 01:47:41 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.10
  Git commit:	0520e24302
  Built:	Fri Mar 23 01:48:12 2018
  OS/Arch:	linux/amd64
  Experimental:	true
```

**Comment by sparklyballs** [comment]
@luvablemarmot are you on the develop branch 


also we have pushed an update on that branch if you are on it and i'd be interested to know if that has solved this for you

and if you're not on the develop branch then there is more headscratching to come

**Comment by luvablemarmot** [comment]
Currently i'm on the latest branch. I'll delete the container and try with develop. Screen shot of latest shown below.
<img width="803" alt="screen shot 2018-04-03 at 7 05 26 pm" src="https://user-images.githubusercontent.com/2404962/38280215-1f5e1e12-3772-11e8-9c80-2fca5978178c.png">

**Comment by luvablemarmot** [comment]
Not having a lot of luck with the develop branch. See below. Will try the latest now.

<img width="1104" alt="screen shot 2018-04-03 at 7 27 49 pm" src="https://user-images.githubusercontent.com/2404962/38280783-304478b8-3775-11e8-8d68-9c6c3548dbd1.png">

**Comment by luvablemarmot** [comment]
Interesting development. I deleted both sonarr containers, restarted the docker daemon on the synology and then downloaded the development image via command line:

<img width="708" alt="screen shot 2018-04-03 at 7 42 18 pm" src="https://user-images.githubusercontent.com/2404962/38281141-2bd8c6ba-3777-11e8-9d3a-0e42cd474621.png">

After doing this, the container comes up properly without MediaInfo error:

<img width="1237" alt="screen shot 2018-04-03 at 7 43 10 pm" src="https://user-images.githubusercontent.com/2404962/38281165-4ec3ee52-3777-11e8-9d6a-d63c734d3206.png">

Could the issue be with synology docker implementation?

**Comment by j0nnymoe** [comment]
Yea this seems like a specific issue with Synology hardware, hopefully whatever it is hasn't caused you an issue since.
