### ISSUE TITLE
High CPU usage on restart

### ISSUE THREAD

**Issue by ksemeks** [linuxserver/docker-sonarr#68]
When i try to restart sonarr via the web ui, the cpu usage skyrockets.
Stopping and restarting the container seems to fix the problem.

mac os high sierra

> sonarr:
>     image: linuxserver/sonarr
>     container_name: sonarr
>     restart: always
>     ports:
>       - 8989:8989
>     environment:
>       - PGID=1000
>       - PUID=1000
>       - TZ=Europe/London
>     volumes:
>       - ${TSRJ}/sonarr:/config
>       - ${DOWNLOADS}:/downloads
>       - ${DOWNLOADS}/complete:/tv

Nothing special in the log. I could see the high cpu usage in docker stats ( 170%, 180%...)
[log.txt](https://github.com/linuxserver/docker-sonarr/files/1935949/log.txt)

**Comment by sparklyballs** [comment]
it's a bit like going to the doctor's and saying it hurts when i do this

don't do it 

if you need/want to restart the app restart the container
