### ISSUE TITLE
Sonarr container "freeze", and can't be stopped/killed

### ISSUE THREAD

**Issue by frankhaugen** [linuxserver/docker-sonarr#69]
My not too complicated system has run radarr for 28+ hours without isssues, then suddenly it cramps up. I tried to stop, kill, remove and otherwise get it going again. Nothing happens, even "docker top sonarr" just hangs

This was running fine until it didn't. I use the same configuration for all my containers, (sonarr, radarr, transmission, jackett, portainer and plex)

I can not see anything happening on the system to trigger this kind of issue

### OS:
Ubuntu Bionic Beaver (Ubuntu Mate)

### Create command
docker create --name sonarr \
-p 8989:8989 \
-e PUID=1000 -e PGID=1000 \
-e TZ=Europe/Oslo \
-v /etc/localtime:/etc/localtime:ro \
-v /home/docker/sonarr/config:/config \
-v /media/tv:/tv \
-v /media/downloads:/downloads \
linuxserver/sonarr

### logs
[sonarrlogs.txt](https://github.com/linuxserver/docker-sonarr/files/1944877/sonarrlogs.txt)

### other
Only thing I did after create was to change the restart policy to "unless stopped". Other containers run smoothly. The

### my theory
Some issue with error-handling that leads to some infinite loop

Anything more you need to troubleshoot this issue?

**Comment by frankhaugen** [comment]
[sonarrlogs2.txt](https://github.com/linuxserver/docker-sonarr/files/1944896/sonarrlogs2.txt)
Logs with timestamps

**Comment by frankhaugen** [comment]
### "sudo docker info"
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: v0.13.0 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-15-generic
Operating System: Ubuntu Bionic Beaver (development branch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.67GiB
Name: home
ID: RA3B:WUQR:NEPL:GRV2:MT4D:4JEE:RRU7:NXIV:NLKQ:CI2T:7CPZ:ZGL3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by frankhaugen** [comment]
I just wiped the system, and did it all from scratch. Issue returns after about 20 hours.

Are anyone reading this issue?

**Comment by sparklyballs** [comment]
you're using (at the time of writing) a dev branch of bionic and i assume a binary release of docker 

i'd start there if i were you because AFAIK no-one else has reported similar issue

**Comment by armsby** [comment]
I have just tried to build a sonarr using this image, and I have the same issue, web interface stalls after 1 min and after sometime the mono process dies and enters a zombi state, this might be linked to mono version as there have been issues with mono 5, but im not sure.

I have not been able to locate the reason for mono dying as I have not had time to look more in to it.

I just wanted to let you know that other people are seeing this issue

**Comment by j0nnymoe** [comment]
Have you tried using the image we provide on Docker Hub instead of building?

**Comment by armsby** [comment]
I just pulled the image linuxserver/sonarr and it gives me the same issue, web runs long enough to load the first page and then it dies before it loads the buttons, mono keeps running according to the log for sometime, but in the end it defuncts and I have to reboot the server to kill the docker

**Comment by sparklyballs** [comment]
@armsby you need to tell us your host OS also

**Comment by sparklyballs** [comment]
because on a fresh pull on one of my machines

![screen shot 2018-05-04 at 10 05 09](https://user-images.githubusercontent.com/4343808/39620329-bb960128-4f82-11e8-9e5b-062216a9ba39.png)

**Comment by armsby** [comment]
I have a backup loaded that works perfect on my server that is not using docker and is on an older version of mono
mono --version
Mono JIT compiler version 3.10.0 (tarball Thu Feb  4 00:22:52 PST 2016)

**Comment by sparklyballs** [comment]
but i can run the docker on essentially the same setup and access the webui 

what is "1.13.1" referring to ?

and can you post your run/create command

**Comment by armsby** [comment]
That is the version of docker I have on a test I build 
armsby@testub:~$ docker --version
Docker version 1.13.1, build 092cba3

**Comment by sparklyballs** [comment]
i wouldn't recommend running or building images with that old a docker version

should concentrate on the machine with up to date version

**Comment by armsby** [comment]
docker create --name sonarr -p 8989:8989 -e PUID=1000 -e GUID=816 -e TZ=Europe/Copenhagen -v /mnt/tv:/tv -v /mnt/config:/config -v /mnt/download:/downloads -v /etc/localtime:/etc/localtime:ro linuxserver/sonarr

it is more or less a copy of the one from the documentation

**Comment by armsby** [comment]
/mnt/download is a NFS
/mnt/tv is a overlayfs 
/mnt/config is SSD in raid5 attached to a local HBA controller

**Comment by j0nnymoe** [comment]
ok, the tv/download paths don't really matter, providing the permissions are fine they will work.
The /config mount, could you try pointing it to somewhere on the local filesystem as a test? for example `/home/username/sonar`

**Comment by armsby** [comment]
the SSD disks are mounted directly in the root of the host system, so unless you expect a linux kernel issue, I can't see what it should help, but I will do it, but I have 9 other containers running the same way also build by your team

**Comment by armsby** [comment]
I am running a container now where /config is located on a single disk without raid or anything, I will let you know the status of it

**Comment by armsby** [comment]
hmmmm, 

it could be that SQLite has issues handling database locking when stored on an md raid5, at the moment it is not diving but I see 
[v2.0.0.5163] System.Data.SQLite.SQLiteException (0x80004005): database is locked
database is locked 

This could indicate that it is having issues loading/processing this large backup and why it is working on my running server as it does not have to process missing metadata, I will let you know of the progress

**Comment by armsby** [comment]
ok now when I have had some more time to dig in to this I think I have found my issue

First it is not a SQLite issue and it runs perfect on an md raid5,
This seams to be bad handling of updates in sonarr, do to the amount of updates from the fact that a backup was being loaded the file systems under my overlaysfs started to become slow, sonarr keeps the logs on the SQLite database until it was done with a hole series, this ofcause causes the webinterface to stall and in the end timeout, in some cases the lock was longer that 120 sec and the process ended up in defunct.


problem was solved by changing the lowerdir order on the overlay, but the cause still exist in sonarr, as scanning of large tv library can cause timeouts that are not handled that well in sonarr

**Comment by armsby** [comment]
@sparklyballs and @j0nnymoe Thank you for all the fast help locating this issue, everything runs perfect again

**Comment by randomparity** [comment]
I'm seeing the same issue with Sonarr simply freezing and wedging docker (i.e. "docker stop sonarr" just hangs, "docker-compose down" returns a timeout error), need to reboot the system to clear.  The system is a dedicated server (not a VM) running Ubuntu 18.04 on a 1TB SSD with an ext4 filesystem (using LVM) but I've also seen the same behavior if install use Ubuntu 16.04.4.  

**Relevant system info:**
# docker --version
Docker version 18.03.1-ce, build 9ee9f40
# docker-compose --version
docker-compose version 1.22.0-rc2, build 6817b533
# docker info
Containers: 7
 Running: 6
 Paused: 0
 Stopped: 1
Images: 8
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-23-generic
Operating System: Ubuntu 18.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.4GiB
Name: dilbert
ID: KW6N:AEC3:FE5H:65VD:MBP7:G27Y:R5PX:3PU2:EVEA:A7EY:LLL2:TK34
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Comment by icebal** [comment]
ive also been having this issue, even .bak'd the config dir and started from scratch. When sonarr refuses to load the webpage after a while, a docker stop fails to.ever stop the container. Running docker top sonarr, it shows mono having gone zombie and never reaped, as well as s6-sync never going away either.

Config is located on ext4 ssd local disk, media is on smb share simce mono has issues with nfs.

Docker version is 18.06-ce, using overlay2. This is also happening to the emby container, but not lidarr or radarr, so im hesitant to say its yet another mono issue....

**Comment by randomparity** [comment]
I noticed that my problem occurred after finishing a file copy so I modified several CIFS settings on the client and server sides and am no longer seeing the issue.

Server Side (QNAP NAS GUI)
- Disabled Recycle Bin support for the share
- Disabled OPLOCK support for the share

Client Side (fstab on Ubuntu Linux):
`//media/Movie	/mnt/media/movies	cifs	iocharset=utf8,credentials=/root/.smbcredentials,**_netdev**,uid=1000,gid=1000,**actimeo=0** 0 0
`
Not sure which particular setting may have helped but I've not seen the problem since making these changes.

**Comment by icebal** [comment]
No recycle bin on my side, its generic linux smb, dont think i have oplock on, will check and update if it is on.

 client side mount is (rw,relatime,vers=default,cache=strict,,uid=1000,forceuid,gid=1000,forcegid,file_mode=0755,dir_mode=0755,seal,soft,nounix,mapposix,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1

Server side config is

#======================= Global Settings =======================
[global]
server min protocol = SMB2
client max protocol = SMB3
workgroup = WORKGROUP
server string = %h server
dns proxy = no
log level = 0
log file = /var/log/samba/log.%m
max log size = 1000
panic action = /usr/share/samba/panic-action %d
encrypt passwords = true
passdb backend = tdbsam
obey pam restrictions = no
unix password sync = no
passwd program = /usr/bin/passwd %u
passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
pam password change = yes
socket options = TCP_NODELAY IPTOS_LOWDELAY
guest account = nobody
load printers = no
disable spoolss = yes
printing = bsd
printcap name = /dev/null
unix extensions = yes
wide links = no
create mask = 0775
force create mode = 0755
directory mask = 0775
force directory mode = 0775
use sendfile = yes
aio read size = 16384
aio write size = 16384
local master = yes
time server = no
wins support = no
map to guest = Bad User

[NAS]
        force user = icebal
        path = /export/mergerfspool
        force group = icebal
        writeable = yes
        public = yes
        browsable = yes
        guest ok = yes

**Comment by icebal** [comment]
Oplock turned off works perfect so far, so it looks like an issue with mono and cifs file locks. lidarr with the oplock default on still has the issue, as does emby if its in the middle of a library scan.

**Comment by medelay** [comment]
To turn off oplock on a wd my book live i used ssh to get in the my book and edited the file: /etc/samba/smb.conf and added: oplocks = false level2 oplocks = false

This seems to be working much better so far.
