### ISSUE TITLE
Container "lost" connection to NFS share

### ISSUE THREAD

**Issue by Bothari** [linuxserver/docker-sonarr#70]
I have recently moved my setup over to a Linux machine ("marvin") with a Synology share ("lededje") to host the actual media files. On the Linux machine I have set up a docker-compose file to run Sonarr, Radarr, etc. The Synology share is mounted on the Linux machine using NFS, set up in the fstab, and provided in the docker-compose file.

Everything was working perfectly, but about 12 hours after starting it all running, the Sonarr and Radarr containers both "lost" the connection to the NFS mount. The mount was still active in the host machine, but Sonarr and Radarr both showed that volume as empty, and they had no permissions to do anything in it. Restarting the containers fixed this issue, and it hasn't reproduced in about 3 days of constant uptime.

Is there a different way that I should connect the NFS share to the container? I am trying to make this setup as reliable as possible with as high uptime as possible, so little things like this will mean I will have to switch to a non-containerized setup, which I would prefer not to do.

## Versions

Ubuntu bionic 18.04
Docker version 17.12.1-ce, build 7390fc6

## fstab

    lededje:/volume1/Share    /nfs/lededje    nfs    defaults    0    1

## docker-compose.yml

	version: '3'
	services:
	
	    sonarr:
	        image: "linuxserver/sonarr"
	        container_name: sonarr
	        ports:
	            - 8901:8901
	        expose:
	            - 8901
	        volumes:
	            - "/etc/localtime:/etc/localtime:ro"
	            - "/var/lib/htpc/sonarr:/config"
	            - "/temp/downloads/complete:/downloads"
	            - "/nfs/lededje/TV Shows:/tv"
	        restart: unless-stopped
	
	    radarr:
	        image: "linuxserver/radarr"
	        container_name: radarr
	        ports:
	            - 8903:8903
	        expose:
	            - 8903
	        volumes:
	            - "/etc/localtime:/etc/localtime:ro"
	            - "/var/lib/htpc/radarr:/config"
	            - "/temp/downloads/complete:/downloads"
	            - "/nfs/lededje/Movies:/movies"
	        restart: unless-stopped

**Comment by aptalca** [comment]
That's how docker works unfortunately.

When you map an nfs mounted location, docker has no idea that it's an nfs share. So if the nfs confection is dropped temporarily, even though your host might reconnect, docker container won't. 

I'd recommend running the containers on the nas of you can do the connections are local

**Comment by Bothari** [comment]
Thanks for the reply, makes total sense when you explain it.

Sadly, I have a non-Intel CPU Synology (DS418), which I understand doesn't have Docker support. I got it rather intentionally (and cheaply) to run as just file serving, with the apps all running on the Linux server. I saw something about a plugin for Docker to mount NFS drives directly, I will do some investigation into that.

**Comment by renaudjumbou-ipssi** [comment]
Hello, i've found some turnaround with that. 
With node-red I listen the sonarr logs with tail and when i detect the disconnection, I send a docker restart by ssh.

**Comment by renaudjx** [comment]
Hello, i've found some turnaround with that.
With node-red I listen the sonarr logs with tail and when i detect the disconnection, I send a docker restart by ssh.
