### ISSUE TITLE
High CPU usage when sonarr tab is open in Chrome (Mac)

### ISSUE THREAD

**Issue by graymattrr** [linuxserver/docker-sonarr#74]
When I have a tab open to sonarr in chrome (mac v67), I can see via task manager that it consumes 100% cpu.  Closing the tab restores normal cpu usage.  I have tried to find a solution online, but have come up short, and am hoping you can point me in the right direction.  To be clear, the cpu pegging is on the browser only, not on the server/docker instance.

Thanks!

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

  Docker (linux)

![screen shot 2018-05-30 at 6 05 49 pm](https://user-images.githubusercontent.com/5082216/40755661-1da67aee-6434-11e8-848c-db31edfa294c.png)

In the logs I am seeing:
`Address already in use. This can happen if another instance of Sonarr is already running another application is using the same port (default: 8989) or the user has insufficient permissions`

As well as:
`System.InvalidOperationException: Sequence contains no elements`

I have seen other reports of a similar problem with one of the two above conditions, and am wondering how to correct this (maybe its something else?).  I have no other services running on port 8989.  

 No symlinks outside of normal Unraid Mapping.

  You guys are great, please keep up the good work!

**Comment by bishpuppy** [comment]
Interestingly enough, I'm not using the docker, my server is CentOS and I am running the apps individually but I have noticed the same thing recently with Chrome on Mac and using Sonarr and Radarr.  CPU is at 100%, the fans kick into high gear and only when I close does it go back to normal.

**Comment by j0nnymoe** [comment]
Closing this issue as it sounds like a sonarr bug rather than a specific container issue.
@graymattrr the issue with the ports on unraid, I'd probably suggest to reboot your box, sounds like a port hasn't been released.
