### ISSUE TITLE
Not working with mergerfs bind mount

### ISSUE THREAD

**Issue by simonvpe** [linuxserver/docker-sonarr#79]
When selecting the destination for a series Sonarr does not see a mergerfs bind mount, but if I mount one of the disks participating in the mergerfs pool it is visible.

**Comment by j0nnymoe** [comment]
Host os? How are you running the container? what's the settings you've used to create the container? Any log files? This information helps otherwise it's very hard work out what the issue is.

**Comment by homerr** [comment]
No further information provided.
