### ISSUE TITLE
ssl support

### ISSUE THREAD

**Issue by timarthurlee** [linuxserver/docker-sonarr#8]
I cannot seem to enable ssl support even after manually configuring the 9898 port in docker to allow it. Is this something that's supported?

**Comment by lonix** [comment]
According to (this)[https://github.com/Sonarr/Sonarr/wiki/SSL] Document, Sonarr requires some windows only software to enable SSL Properly. We Will not cater to this. May i suggest useing somehting like a proxy outside the container. Personally i use (this) [https://github.com/jwilder/nginx-proxy] ub ny oruvate setup.
