### ISSUE TITLE
Needs ability to set download client order and load balance to them.

### ISSUE THREAD

**Issue by RCFilm** [linuxserver/docker-sonarr#80]
Needs ability to set download client order and load balance to them.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by j0nnymoe** [comment]
We only package sonarr, we don't develop it. Suggest that to the developers.
