### ISSUE TITLE
Owner/Group for /config files

### ISSUE THREAD

**Issue by ftolead** [linuxserver/docker-sonarr#86]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

 Ubuntu 18.04.1
 docker run -it --rm -e TZ=America/Phoenix --mount type=bind,source="/media/tv-shows",target=/media/tvshows --name sonarr -d -p 8989:8989 ubuntu-sonarr /bin/bash

**Comment by j0nnymoe** [comment]
And the issue is?

**Comment by ftolead** [comment]
I'm "dockerizing" my regular services so I need to preserve their configs to use with the docker images I create.

When running my sonarr container with an interactive shell, nzbdrone is throwing an error while constantly trying to restart the service:

> [Fatal]
> ConsoleApp:
> EPIC FAIL! 
> [v2.0.0.5252]
> NzbDrone.Core.Datastore.CorruptDatabaseException:
> Database file: /config/nzbdrone.db is corrupt

I've copied my currently running sonarr configuration files and db's from ~sonarruser/.config/ to /root/config prior to building

For my first run I use an interactive shell to ensure everything is kosher, before I create a systemd startup file.

While I was in the interactive shell I was able to fix this error by changing the owner/group of the /config files from root:root to abc:abc

Sonarr then started normally

**Comment by j0nnymoe** [comment]
Have you read our read me? We provide instructions on how to run this ther,. You don't need to manually build this yourself.

**Comment by ftolead** [comment]
I'm looking through the read me now. In the mean time I've added the following to my root/etc/cont-init.d/30-config file:
chown -R abc:abc \
	/config

and built a new image. This fixed the issue I had. I'm sure if I was running this as standard image instead of manually building I would not have this problem.

**Comment by j0nnymoe** [comment]
Yep, I would recommend running the image we build and publish to hub.docker.com.
