### ISSUE TITLE
MP4 Automator Support

### ISSUE THREAD

**Issue by kylerw** [linuxserver/docker-sonarr#9]
Would love support for: https://github.com/mdhiggins/sickbeard_mp4_automator/

it might make sense to have NZBGet / SABnzbd support this rather than each PVR application. Ultimately I'm looking for a way to automate the remux processor to help out my process and limit transcoding requirements for Plex. Where that lives, I'm not sure I care too much (personally).

**Comment by lonix** [comment]
Im looking into this. Just don't quite know how to handle this thing yet (Due to many sources to destinations.)

**Comment by lonix** [comment]
So this is getting handled in the following way, we are now (jan 1) adding support for you to supply your own script to be executed at the end of startup in our baseimage, thus writing a script that installs the packages needed should suffice. (this will be not so documented. so join our irc channel once this is inplace to get more info on it). This is to keep it simple for the avrage user and yet provide the support for advanced users.

**Comment by gts24** [comment]
Hello, Could I please get the details on these options for sonarr? I want to make sure all downloads are mp4 format. thanks

**Comment by tobbenb** [comment]
There are no option to run your own scripts anymore.

**Comment by kylerw** [comment]
@gts24 you'll have to run any scripts manually if you want to get it setup with Sonarr since the auto-run functionality has been removed. I created a script I use with my NZBGet container (https://github.com/kylerw/MiscScripts/blob/master/NZBGet-Alpine_MP4Automator) if you are interested in taking a look at what it may need to look like.

**Comment by gts24** [comment]
@kylerw belated thanks here.
