### ISSUE TITLE
Indexers: There was an error loading this item

### ISSUE THREAD

**Issue by oliverjhyde** [linuxserver/docker-sonarr#98]
Decided to try out Sonarr-V3 using Docker on Unraid but since the last update (unsure if the update actually caused this however) trying to edit indexers gives the error - There was an error loading this item and under details gives this
TypeError: props.value is null

    in NumberInput
    in div
    in div
    in div
    in FormInputGroup
    in div
    in FormGroup
    in ProviderFieldFormGroup
    in div
    in Form
    in div
    in div
    in Scroller
    in ModalBody
    in div
    in ModalContent
    in EditIndexerModalContent
    in EditIndexerModalContentConnector
    in Connect(EditIndexerModalContentConnector)
    in ErrorBoundary
    in div
    in div
    in div
    in Modal
    in EditIndexerModal
    in EditIndexerModalConnector
    in Connect(EditIndexerModalConnector)
    in div
    in div
    in Card
    in Indexer
    in div
    in div
    in PageSectionContent
    in fieldset
    in FieldSet
    in Indexers
    in IndexersConnector
    in Connect(IndexersConnector)
    in div
    in div
    in div
    in Scrollbars
    in OverlayScroller
    in PageContentBody
    in Connect(PageContentBody)
    in div
    in DocumentTitle
    in SideEffect(DocumentTitle)
    in ErrorBoundary
    in PageContent
    in IndexerSettings
    in Connect(IndexerSettings)
    in Route
    in Switch
    in Switch
    in AppRoutes
    in div
    in div
    in Page
    in PageConnector
    in Connect(PageConnector)
    in Route
    in withRouter(Connect(PageConnector))
    in Router
    in ConnectedRouter
    in Provider
    in DocumentTitle
    in SideEffect(DocumentTitle)
    in App

**Comment by aptalca** [comment]
You should ask on sonarr's GitHub. It sounds like an app issue rather than container.
